### ISSUE TITLE
Build 302 *TEST*

### ISSUE THREAD

**Issue by jhdvp** [Nummer/Destroy-Windows-10-Spying#10]
Здравствуйте!
Останавливается прогресс и стоит на месте при попытке отключения таска офиса: "[11:47:12] Disabled task: Microsoft\Office\OfficeTelemetry\OfficeTelemetryAgentLogOn2016". В планировщике заданий посмотрел, таск находится в отключенном состоянии.
![qwe](https://cloud.githubusercontent.com/assets/11536840/9436746/3a7e8d10-4a5a-11e5-87ae-eaec698b9d6d.png)

**Comment by Nummer** [comment]
ну вы читайте заголовок. UNSTABLE . А в релизах помечен как пре релиз ) Тут баги есть , я не спорю.

**Comment by jhdvp** [comment]
Я понимаю, поэтому и решил сообщить. -)
