### ISSUE TITLE
Windows 10 stopped to update

### ISSUE THREAD

**Issue by yursi** [Nummer/Destroy-Windows-10-Spying#102]
I have downloaded the DWSLite source codes (Destroy-Windows-10-Spying-master.zip, 706,371 bytes, version 448), compiled them, run and applied. I have selected "Delete Windows 10 Metro applications" and pressed "Destroy Windows 10 Spying" button". After restart my Windows 10 Home tried to download KB3087040, but stuck at 0%. Is this intended? have I completely loose the ability to update Windows? What is the firewall rule that I should unblock to turn off updates back?

**Comment by TRoskop** [comment]
Hi @yursi ,
are you able to install the other updates?

**Comment by yursi** [comment]
Thank you, after second Windows restart the update has been downloaded and installed. I will monitor what will be with the forthcoming updates.
