### ISSUE TITLE
Firewall rule blocking Hotmail Sync.

### ISSUE THREAD

**Issue by neoatomic** [Nummer/Destroy-Windows-10-Spying#103]
I'm having an issue with one of the Firewall rules and release 448.
My Windows live mail has 3 Hotmail accounts setup, but 1 refused to sync.
As both others where working fine it never occurred to me that it could be the firewall causing the problem.

But a long story short, the below ip range block is preventing the syncing for that Hotmail account.
If i disable it, the syncing works again.

```
157.55.235.0-157.55.235.255_Block
```

To make it even more strange, if i modify the ip rage for that rule to block even 1 IP the sync doesn't work anymore. Only disabling the rule works. 

Not sure what is blocked in this rage, but hopefully you could take a look.

**Comment by Nummer** [comment]
this is spying ip's range.

**Comment by neoatomic** [comment]
Did some more testing and the `157.55.235.55` IP is the problem. I changed the rule to block : 

`157.55.235.0-157.55.235.54`
`157.55.235.56-157.55.235.255`

Did try to block `157.55.235.55` and add an exception for 1 program, but that doesn't seem to work as Deny overrules Allow... :( 

So i left `157.55.235.55` out of the rage so that Hotmail account with Windows Live Mail works.
Any specifics where that IP is used for by MS.?
