### ISSUE TITLE
re-enable windows defender

### ISSUE THREAD

**Issue by SiNaPsEr0x** [Nummer/Destroy-Windows-10-Spying#104]
this option dont work! ... please re-enable defender for fix this flag

**Comment by Baigle** [comment]
Windows Defender sucks, really. Why would you want this?

**Comment by TRoskop** [comment]
It might be that defeneder "sucks", but if he wants it or needs it he should be able to use it.

**Comment by Baigle** [comment]
Yes, I apologize, but I won't withdraw my statement. I will post these, however:

Av-comparatives.org
av-test.org
virusbtn.com
virustotal.com
herdprotect.com

**Comment by Nummer** [comment]
no. sry
