### ISSUE TITLE
Settings unavalible on Win7 x64 SP1

### ISSUE THREAD

**Issue by mikhaelkh** [Nummer/Destroy-Windows-10-Spying#105]
All settings are unavalible so I can't configure what I want to remove. You should disable configuring only settings which are unrelevant to installed OS.
![dws1](https://cloud.githubusercontent.com/assets/8005688/10400343/c3e14a4a-6ec0-11e5-8632-61c6419e5152.jpg)

**Comment by Nummer** [comment]
ok

**Comment by Nummer** [comment]
fixed in new version ;)

**Comment by mikhaelkh** [comment]
Settings folder is still unconfigurable.

**Comment by Nummer** [comment]
=\
ok

**Comment by mikhaelkh** [comment]
Build 528 still has no settings on win7x64;( I understand that most settings are for windows 10, but gimme at least some! And reopen the issue!

**Comment by mikhaelkh** [comment]
Настройки до сих пор недоступны в Windows 7! Конечно многие настройки не для семерки, но она тоже поддерживается. Также хочется в настройки пункт "удалить шпионские обновления"!

**Comment by mikhaelkh** [comment]
Replace "and I forget what else to added" with "and I forgot what else was added" in releases.

**Comment by Nummer** [comment]
TODO: Add

**Comment by Nummer** [comment]
The program is not designed for Windows 7. It is designed exclusively for Windows 10. For Windows 7 \ 8.1 is simply not supported.

**Comment by mikhaelkh** [comment]
Nummer said:
>The program is not designed for Windows 7. It is designed exclusively for Windows 10. For Windows 7 \ 8.1 is simply not supported.

From `README.md`: 
- Support Windows 7/8/8.1/10 or Server 2008-2012 R2

From http://dws.wzor.net/: 
- Destroy Windows Spying - is the most popular program to remove spyware in Windows 7/8.1/10

So I guess Windows 7 is supported, please tell me otherwise.
