### ISSUE TITLE
NCSI (Network Connectivity Status Indicator)

### ISSUE THREAD

**Issue by th3m** [Nummer/Destroy-Windows-10-Spying#107]
This privacy issue is fixed just through the blocking hosts file, or the "regedit" along with the "Local Computer Policy Editor" editing still needs to be done?

http://www.digitalmunition.me/2015/06/how-microsoft-can-spy-on-you-and-how-to-stop-it/

**Comment by Baigle** [comment]
Usually the gp editor only changes registry values.
