### ISSUE TITLE
PRIVACY VS Cortana (Destroy Windows 10 Spying v1.5.302)

### ISSUE THREAD

**Issue by javi97** [Nummer/Destroy-Windows-10-Spying#108]
Hi, first of all thank you for your time and also excuse me for my poor english but I'm not english so I'll do my best xD

The subject is that I have tried your software "Destroy Windows 10 Spying v1.5.302" in several computers and there's something I want to ask you about. I find your program really nice but the thing is that after using it "Cortana" doesnt work anymore. I suppose it's because of the option "Disable private settings" in your software. The question is: Is it possible to run Cortana without giving to her my location and my contacts?

To finish with I wanted to ask a last thing: after using your program if I manually want to reactivate contacts for being able to use Cortana for example, I dont know why but I can't change contacts permissions! I have tried in several computers and it happens the same.

Sorry for the inconvenience.
I attach a pair of images for you to see. Thanks
![image1](https://cloud.githubusercontent.com/assets/15066031/10412434/03048a64-6f86-11e5-81e5-446ef2b67c8c.png)
![image2](https://cloud.githubusercontent.com/assets/15066031/10412435/03088e0c-6f86-11e5-86b6-5bc9776dc52f.png)

**Comment by TRoskop** [comment]
Cortana can - as far as I know - not work without those permissions.
I tried to run cortana while I deactivated the location and cortana asked me to enable it.


Date: Sat, 10 Oct 2015 10:37:27 -0700

**Comment by javi97** [comment]
So how can I revert the changes your program made? Because now I can't turn on Cortana and also Windows doesnt let me change "Contacts" privacy:
![image2](https://cloud.githubusercontent.com/assets/15066031/10412435/03088e0c-6f86-11e5-86b6-5bc9776dc52f.png)

**Comment by TRoskop** [comment]
The easiest way might be to use the windows recovery. Normally, DWS_Lite creates a restore point before changing something. So windows is able to go back to this state reverting all changes.
For more information go here http://windows.microsoft.com/en-us/windows-8/restore-refresh-reset-pc and tap "Restore your PC to an earlier point in time"

**Comment by javi97** [comment]
So isnt there any other way to manually do it without having to restore? Because I used your program some weeks ago and I'm not pretty interested in restore to a point from 2 weeks ago...

Thanks.

**Comment by Baigle** [comment]
Group Policy editor uses the same registry values as a lot of these spying protections

**Comment by bimbam123** [comment]
To enable contacts you need to open regedit.exe and go to:

HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\DeviceAccess\Global\{7D7E8402-7C54-4821-A34E-AEEFD62DED93}

Just change the string "Value" from "deny" to "allow"

**Comment by javi97** [comment]
Thank you very much bimbam123, that solved my problem and also my question. Grateful of people like you!
Now this post is closed for real :)
