### ISSUE TITLE
Module "to get windows 10"

### ISSUE THREAD

**Issue by gegemon2012** [Nummer/Destroy-Windows-10-Spying#109]
Module "to get windows 10"
After starting the program Reset exceptions update installation module "to get windows 10 'and re-install the update 3035583, 2952664, 3021917. It would be desirable that they, too, were excluded from the program updates and not placed again. It is not clear why almost all program settings are inactive in windows 7 ...

**Comment by TRoskop** [comment]
This Program is primary Designed for Windows 10!

Date: Sun, 11 Oct 2015 05:05:16 -0700

**Comment by gegemon2012** [comment]
I thought that if you specify "Windows 7" under the program and the operating system is suitable. Is it possible to implement full functional (I'm talking about those functions which are needed for Windows 7) for Windows 7?
