### ISSUE TITLE
Blocked Telegram requests from IE

### ISSUE THREAD

**Issue by hooddy** [Nummer/Destroy-Windows-10-Spying#110]
After use DWS IE stop correctly resolve Telegram requests like
tg://resolve/?domain=wpseven
tg://addstickers/?set=Cowardly_Dog
I've get this one error
![default](https://cloud.githubusercontent.com/assets/6899176/10424659/9ca17b42-70d9-11e5-9dd6-59b37bd556aa.png)
Please check it out.

**Comment by Nummer** [comment]
working.
