### ISSUE TITLE
Can't Revert Old Settings

### ISSUE THREAD

**Issue by kunfuninja12** [Nummer/Destroy-Windows-10-Spying#111]
I want to revert back to the old settings but i can't I want to help Microsoft develop windows 10

**Comment by TRoskop** [comment]
Hi @kunfuninja12 .
You could try to reset your computer to its former state. 
Here you'll find more information: http://windows.microsoft.com/en-us/windows-8/restore-refresh-reset-pc

**Comment by kunfuninja12** [comment]
yeah i dont want to re format

**Comment by kunfuninja12** [comment]
Yeah. i dont want to re format

**Comment by TRoskop** [comment]
Please see the 'Restore your PC to an earlier point in time' section.
