### ISSUE TITLE
Skype won't connect

### ISSUE THREAD

**Issue by kirillkovalenko** [Nummer/Destroy-Windows-10-Spying#112]
Skype stopped connecting after using the DWS. 
I had to revert firewall settings back.

**Comment by Nummer** [comment]
Download the latest version. It fixed.

**Comment by skyr1s** [comment]
For Skype: 8.16.0.4 comment in hosts:
`# 0.0.0.0 login.live.com`
It works for me

**Comment by Notasinbeer** [comment]
@skyr1s 
For Skype: 8.16.0.4 comment in hosts:
# 0.0.0.0 login.live.com
It works for me

That's what I did, just edit file host.
