### ISSUE TITLE
Small bugs on windows 7 x64

### ISSUE THREAD

**Issue by gegemon2012** [Nummer/Destroy-Windows-10-Spying#114]
Small bugs on windows 7 x64 ...
Options still not active. The utility is inactive enabling / disabling UAC.
Thank you for your responsiveness and efficiency.

**Comment by Nummer** [comment]
![image](https://cloud.githubusercontent.com/assets/7760838/10519512/b92f003a-736e-11e5-84d1-fb7d2d6fa9f4.png)
![image](https://cloud.githubusercontent.com/assets/7760838/10519519/c01662d0-736e-11e5-9592-0dc9f01420d9.png)
