### ISSUE TITLE
Utilities: Remove all old DWS Firewall rules

### ISSUE THREAD

**Issue by verum-est** [Nummer/Destroy-Windows-10-Spying#115]
Greetings! 

I personally find his tool is very useful! in terms of privacy/security, and I believe the said subject is a new feature but it seems to be not working on my end, even after system restart on Win7-x86-SP1... 

Please help/fix. For your consideration.

Thank you in advance and for all your hard work -Kudos!
 
All the best!
@verum_est(Twitter)

**Comment by Nummer** [comment]
TODO: ADD

**Comment by Nummer** [comment]
function works perfectly.
