### ISSUE TITLE
Feature Request: An option to whitelist Skype

### ISSUE THREAD

**Issue by verum-est** [Nummer/Destroy-Windows-10-Spying#116]
Hi @Nummer,

Good day! 

Let me say thank you for creating this very useful tool! -for free!

I'm not sure where to submit feature requests for this awesome tool, but I think this is also a concern for all 'Skype' users: 

We all know that Skype is one of MSFT's so called spying tools, but many still uses it for their everyday communication. Having said that, after using this great tool and restarting the system, I found out that I cannot anymore update my Skype, even by going online and download the upgrade manually from a browser.

I believe this is caused by the firewall list(or Host file list?) being added by the tool. I'm a little lost here, just like many others, how to fix or know a workaround for this matter.

With this, I do hope that you would consider adding an option for the users whether or not to include(white-list) everything Skype-related on your next stable-build release.

Of course, suggestion(s) and feedback are most welcome! 

Again, a BIG Thank You for creating this tool!

All the best!
@verum_est(Twitter)

**Comment by Nummer** [comment]
I blocked only dangerous spyware domains Skype.
