### ISSUE TITLE
its not a bug i wanna help you about turkish translate.

### ISSUE THREAD

**Issue by TurkishSword** [Nummer/Destroy-Windows-10-Spying#118]
hi! its a great software for humanity. thanks for that first. i just want to make a Turkish translate for the software to get more people to this software. thx a lot. and i will be happier if you contact me from my e-mail ! h.nevzatdemirel@hotmail.com  or   nevzat.tarantula@gmail.com

**Comment by TRoskop** [comment]
Hello @TurkishSword ,
It is always good when people want to help.

It is simple to add your language. In the following I assume you are not a developer so I will show you a simple guide.

First, go to this page https://github.com/Nummer/Destroy-Windows-10-Spying/blob/master/DWS/lang/en-US.resx#L120 and download the document.
Now you can translate each string (and only them!) into your language.

When done, you can send me the file ( t.roskop@hotmail.de ) and I will complie into the project and take all the other necessary steps.
Then I will publish it to this project where @Nummer has to accept the change and that would be all.

So, let's try it. If you have questions, you can ask me via email.

Thomas

**Comment by TurkishSword** [comment]
thanks for reply !  i will be pleasured to help you. it will be done as
soon as possible.

2015-10-17 21:13 GMT+03:00 Thomas Roskop <notifications@github.com>:

**Comment by TRoskop** [comment]
Wow, your response was very fast :exclamation:

**Comment by 6c6c6** [comment]
It's not so easy. My [ukrainian translation](https://github.com/Nummer/Destroy-Windows-10-Spying/pull/85) isn't included [yet](https://github.com/Nummer/Destroy-Windows-10-Spying/tree/master/DWS/lang).

**Comment by TRoskop** [comment]
Well, this is neither your nor my fault. @Nummer just does not want to include the translations.
I don't know why but sometimes he is acting weird.

**Comment by TurkishSword** [comment]
is he ignored turkish translation ?

**Comment by TRoskop** [comment]
So, finally I created the pull-request to add the new code.
See here: https://github.com/Nummer/Destroy-Windows-10-Spying/pull/120
Now it is in @Nummer 's hands to accept it. Good luck.

**Comment by TurkishSword** [comment]
ah thanks a lot that made my day :D

**Comment by Nummer** [comment]
add
