### ISSUE TITLE
Failed to load from network

### ISSUE THREAD

**Issue by TRoskop** [Nummer/Destroy-Windows-10-Spying#119]
Hello,
as some might have found out it is not possible to use the program when loading it from network drive.
Workarround: Copy the file to the desktop or so and run it.

Reason: When calling *Icon = Icon.ExtractAssociatedIcon(Application.ExecutablePath);*, the netowkr-drive path is not a valid path for this function.

Note: In my next pull-request adding the turkish language (thanks to https://github.com/Nummer/Destroy-Windows-10-Spying/issues/118) I will also add a fix.

**Comment by Nummer** [comment]
THANKS! Issue 4 FIX!
