### ISSUE TITLE
Feature request: more settings

### ISSUE THREAD

**Issue by sniperle** [Nummer/Destroy-Windows-10-Spying#122]
There is a tool named "O&O ShutUp 10" which shows many privacy settings that are still (de)activated even after running DWS. Maybe you can include some (or all) of these options. Thanks.

The URL to the tool is:  http://www.oo-software.com/en/shutup10

**Comment by Nummer** [comment]
There's a lot of unnecessary settings. This program does essentially nothing. I post her source in my twitter.
