### ISSUE TITLE
новая DWS 528ver

### ISSUE THREAD

**Issue by metaxer** [Nummer/Destroy-Windows-10-Spying#125]
SmartScreen блокирует прогу, а предыдущая версия (500) работает нормально - Тестил  на только что установленной винде с образа диска созданном утилитой МС 

На 500 версии не понятно как работает Удаление или Отключения Обновлений Windows, так как нет ни каких уведомлений о успешном действии или

**Comment by Nummer** [comment]
Отключение обнов - это отключение службы обновлений. 

Игнорируйте смарт скрин на новую версию.

**Comment by metaxer** [comment]
Не понимаю, как его можно игнорировать? Программа просто закрывается =\ В диалоговом окне СмартСкрина нет ни каких вариантов этого избежать, оно лишь уведомляет о закрытии приложения DWS_Lite
