### ISSUE TITLE
Removes "good" updates?

### ISSUE THREAD

**Issue by Netkuszkusz** [Nummer/Destroy-Windows-10-Spying#127]
Hi! Why the v528 removes these important-type updates? (Win 7 x64)

* Cumulative Security Update for Internet Explorer 11 for Windows 7 for x64-based Systems ([KB3093983](https://support.microsoft.com/en-us/kb/3093983))
* Security Update for Windows 7 for x64-based Systems ([KB3088195](https://support.microsoft.com/en-us/kb/3088195))
* Update for Windows 7 for x64-based Systems ([KB3083710](https://support.microsoft.com/en-us/kb/3083710))

It's in the log too:
...
[INFO] Remove update KB3088195
[INFO] Remove update KB3093983
[INFO] Remove update KB3083710

**Comment by Nummer** [comment]
this spying updates. 
I'm using the Reversing-Engineering examined them.
