### ISSUE TITLE
Error add to hosts.

### ISSUE THREAD

**Issue by RJOflodor** [Nummer/Destroy-Windows-10-Spying#129]
I thought Spybot Anti-beacon has something to do with this error because I've set it to run with Windows. So, I ran it again without it but the same error pops up. This started from the previous version. The one before this 528 build.

Error log:
"Error add to hosts. Message: Access to the path 'C:\Windows\System32\drivers\etc\hosts' is denied."

DWS log:
"[WARNING] Windows Restore DISABLE
[INFO] Latest version number: 528"

I attached pop-up picture with this message.

**Comment by Nummer** [comment]
disable you antivirus.

**Comment by RJOflodor** [comment]
Thanks Nummer!
