### ISSUE TITLE
Reenable Windows Defender

### ISSUE THREAD

**Issue by PCMRStudio** [Nummer/Destroy-Windows-10-Spying#131]
Is it possible to reenable win def, after deactivating it?

**Comment by Baigle** [comment]
#104

**Comment by Baigle** [comment]
Edit this registry script and replace the 1's with 0's... it was made to disable defender, gods only know why you would want to enable it again.. maybe to try and drive someone insane, maybe to use the completely useless software and trick them into thinking they are secure, maybe to spy on them by allowing M$ to collect their data... who knows? if you want to re enable it go ahead and be the hero you've always wanted to be, but its on your hands.

Paste the below into notepad, edit the DWORD values from 1's to 0's at the ends, save the file as EnableMicrosoftSpyingCrapware.reg (or anything ending in .reg) and be on your unwitting way.

Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender]
 “DisableAntiSpyware”=dword:00000001
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection]
 “DisableBehaviorMonitoring”=dword:00000001
 “DisableOnAccessProtection”=dword:00000001
 “DisableScanOnRealtimeEnable”=dword:00000001
