### ISSUE TITLE
system language is Arabic , but the program starts in Turkish

### ISSUE THREAD

**Issue by Hossainrizg** [Nummer/Destroy-Windows-10-Spying#133]
my system language is Arabic , but the program starts in Turkish
I think the problem is here 
https://github.com/Nummer/Destroy-Windows-10-Spying/blob/master/DWS/DestroyWindowsSpyingMainForm.cs#L289

**Comment by Nummer** [comment]
TODO: Fix

**Comment by Hossainrizg** [comment]
still waiting for fix

**Comment by Hossainrizg** [comment]
still waiting for fix

**Comment by Nummer** [comment]
fixed in new version
