### ISSUE TITLE
integration

### ISSUE THREAD

**Issue by dogecastle** [Nummer/Destroy-Windows-10-Spying#136]
hey, not a bug. i tried to integrate this program in windows 10 installation using the /destroy command and ntlite but it asked me to restart. could you include an option that doesnt ask to restart?

thanks you

**Comment by Nummer** [comment]
TODO: Fix

**Comment by Nummer** [comment]
Fixed in new version

**Comment by wineperm** [comment]
[ERROR] Error add HOSTS в логе, как исправить?

**Comment by Nummer** [comment]
disable your antivirus
