### ISSUE TITLE
Не помогает на 7

### ISSUE THREAD

**Issue by Tishak** [Nummer/Destroy-Windows-10-Spying#141]
На Windows 7 x 64 Pro все встает назад с обновлением и комп теперь виснет при работе с браузером , торрентом и текстами, а в 3D играх почему-то нет.

**Comment by Nummer** [comment]
А зачем вы устанавливали обратно эти обновы?

**Comment by Tishak** [comment]
Вручную поставить?

29.10.2015, 16:36, "Nummer" <notifications@github.com>:
