### ISSUE TITLE
Really need remove some updates?

### ISSUE THREAD

**Issue by Rootzpower** [Nummer/Destroy-Windows-10-Spying#142]
First of all, thank you for your excellent work.

When I use the Destroy-Windows-10-Spying noticed that you are removing updates that have some doubts whether it is even necessary to remove.
According to the DAZ user of mydigitallife forum are being removed updates that are harmless.

I leave here the list and the link to the comment of DAZ:

http://forums.mydigitallife.info/threads/64561-Remove-Telemetry-and-Windows-10-Related-Updates-from-Windows-7?p=1167160&viewfull=1#post1167160

###########################################
KB2922324 isn't available
KB2976978 applies to Windows 8.x
KB3012973 isn't available
KB3015249 isn't available
KB3042058 is harmless?
KB3044374 applies to Windows 8.x
KB3083324 is a Windows update client
KB3083325 applies to Windows 8.x
KB3083710 is a Windows update client
KB3088195 is harmless?
KB3093513 is harmless?
KB3093983 is harmless?
KB971033 is used for activation and is totally harmless

IMO you're fighting an uphill battle because it'll get to the point where Microsoft will release security updates that are built off of the files that include telemetry. So you'll either have to update and deal with it or run a vulnerable version of Windows.

Having some of the updates installed e.g. KB3050265 is essential unless you want to suffer from a massive memory leak that also pegs your CPU at 100%. 
#########################################################

**Comment by Nummer** [comment]
KB3050265 - download windows 10 update (windows update fix) .
