### ISSUE TITLE
After running the update and delete program is not making them hidden updates.

### ISSUE THREAD

**Issue by gegemon2012** [Nummer/Destroy-Windows-10-Spying#144]
After running the update and delete program is not making them hidden updates. After starting the Update Center had to be added manually checking the logs. OS Windows 7 x64

После запуска и удаления обновлений программа не делает их скрытыми обновлениями. После запуска центра обновлений пришлось добавлять вручную сверяясь с логами. OS Windows 7 x64

**Comment by Baigle** [comment]
The updates that are deleted with the tool are just showing up again in Windows Updates, forcing you to check the logs and hide the bad updates manually afterwards?

Not sure if I got the interpretation right, but hope it helps clarify.

**Comment by gegemon2012** [comment]
Yes! Your understand me, Excuse me for my bad English...

**Comment by verum-est** [comment]
These are called persistent updates. With this, you may have to hide all the unnecessary updates manually, for them not to show up again on the list. You may also need to change the settings on how your system looks up for any updates. Hope this helps! - Cheers!

**Comment by iki** [comment]
@Nummer @verum-est: it would be actually really useful to automatically hide the uninstalled updates:

1. No DWS user wants the removed updates to be installed again.
2. It's confusing that windows update offers them again. Or even installs them directly if it is set for automatic updates.
3. And it's tedious to check updates one by one against `DWS.log` and hide them manually.

**Comment by Baigle** [comment]
Having it hide them automatically is great addition, even hiding the continually reappearing Silverlight and Windows 10 Upgrade "updates" is getting annoying. :)

I can only imagine how bad it will be when they force the Upgrade to Win10 onto the recommended updates section in 2016, can't wait at all..

**Comment by iki** [comment]
@Baigle I hope DWS will be able to keep up and block it ... and I don't expect MS to be able to stop publishing win7/8 updates before some reasonable time because of businesses running it.

The big reason behind requesting to disable uninstalled updates is that I want to spead DWS to family and friends and would need it to be as simple as possible, ie. not having to give them list of KB codes that they need to hide in windows update after DWS run. Esp. if I ask them to run it regularly, or setup a task for it on their machines.

**Comment by gegemon2012** [comment]
If you continue iki thought it would be nice to do the service of DWS that would automatically updated / update the database in the case of ubdate was start in the hidden / open mode.

**Comment by aallinen** [comment]
There is vbs script to do hiding of updates
http://superuser.com/questions/722667/how-to-hide-updates-in-windows-updates-without-gui.
Could you integrate operations to DWS to automate hide?

**Comment by Baigle** [comment]
This looks really pleasing to the eyes: http://forums.dimmdrive.com/index.php?/topic/1422-dev-here-for-you-windows-10-users-ive-got-something-new-coming/

More devs are starting to make similar utilities to get rid of some of the spying junk, but none as deep as this that i've seen.. even advanced system care 9 pro has new win10 privacy helper settings
