### ISSUE TITLE
crash (build 600) + new IP 

### ISSUE THREAD

**Issue by winap2** [Nummer/Destroy-Windows-10-Spying#145]
When I modify host over the program, than freeze and crash.
Modify-open in text editor-add IP-ctrl+s......freeze and crash.
And my personal ESET smart security show very often these ip adress akamaitechnologies.com 104.96.147.3, deploy.static.akamaitechnologies.com 23.57.107.27 and  23.57.107.163, 23.57.101.163
When I open new program, when I install..my firewall show this..but no comodo firewall. Is this IP adress NSA or what? Thanks, winap

**Comment by Nummer** [comment]
fixed. Thx

**Comment by winap2** [comment]
Hi Nummer, Yesterday I edit (add and delete) some IP adress, can you check it once again please? 
Now I add some site on next post down..sorry for my poor english, man :D
Have a nice day, 
Thanks
