### ISSUE TITLE
Missing Telemetry Entries

### ISSUE THREAD

**Issue by FAKUMSW10** [Nummer/Destroy-Windows-10-Spying#147]
Not a bug, please check these entries and if you agree add them to the list

0.0.0.0	choice.microsoft.com.nstac.net
0.0.0.0	settings-win.data.microsoft.com
0.0.0.0	vortex-bn2.metron.live.com.nsatc.net
0.0.0.0	vortex-cy2.metron.live.com.nsatc.net
0.0.0.0	vortex-bn2.metron.live.com.nsatc.net
0.0.0.0	vortex-cy2.metron.live.com.nsatc.net

**Comment by Nummer** [comment]
=\
