### ISSUE TITLE
DWS Lite build 600 hangs

### ISSUE THREAD

**Issue by github-user-cdn** [Nummer/Destroy-Windows-10-Spying#149]
Attach is a screen shot of where DWS app is at... seems to be frozen/stuck at 'Disable Telemetry' and it's been more than 7+ mins. The PC I'm working on has 2 accounts (admin and user). I first ran app on admin account and it was fine, but not now in user account with admin rights as shown in attach. Prior to build 600, I had no problem running on both accounts and I always execute the app 'Run as administrator'. I've restarted the PC couple times and no result. 

![dws hangs - nov0315](https://cloud.githubusercontent.com/assets/15633381/10911736/70d71e8c-8203-11e5-905b-336713050c15.PNG)

**Comment by Nummer** [comment]
fixed
