### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by pengjunjie1207** [Nummer/Destroy-Windows-10-Spying#155]
After I download the DWS_Lite.exe (Build 637), Windows Defender reports that Trojan:Win32/Spallowz.A!plock is detected. My OS is Windows 10 build 10576.

**Comment by winap2** [comment]
What? Its clean! Look..
https://www.virustotal.com/en-gb/file/da05c7d3a828a399ed94c7013ad76a4dd83b5a7a6cf5896d165e4327f8e4e9b0/analysis/1446842822/

And stop use defender, ESET is better. Avast slows PC, but I thing is good. Mabe Kaspersky..

**Comment by pengjunjie1207** [comment]
I have checked the md5 and the sha1 of DWS_Lite.exe and they are the same as those of yours. Maybe Windows Defender reports the issue because Microsoft adds the software into the blacklist of Defender. And the reason.. :)

**Comment by Baigle** [comment]
Very good point.

This PogoCheats site has a similar issue with Defender: http://www.pogocheats.net/forum/index.php?topic=46657.0

"I'm guessing Windows Defender does not like that the bot is creating / modifying the BSB files (BingSearchBot.ini, BingCredits.txt, etc)."

And it would seem Nummer's other repository https://github.com/Nummer/CheatsLib may have some similarities to the bot software they were using, leading to a false positive.

Same thing for ENB in Skyrim recently: http://forums.nexusmods.com/index.php?/topic/3326495-windows-defender-suddenly-detecting-enb-at-trojan/
