### ISSUE TITLE
Defender, Customer experence, 

### ISSUE THREAD

**Issue by winap2** [Nummer/Destroy-Windows-10-Spying#156]
Hi Nummer, 
Can you please integrate "Disable Defender" and full disable Customer Experience Improvement?
Because when I look on Task scheduler-Microsoft-Windows-Customer Experience Improvement, I see(when I onlick consolidator, Kernel Ceip, USB Ceip) is all ENABLED! Yes, Its really enabled.(triggers-status-"onclick"enabled-to tick off and now I see disabled. Enter and quit.
And next telemetry is in WMP.
Option-Privacy-WMP upgrading software on the basis of experience. I think the same is in Windows 8.
THX
Winap

**Comment by Nummer** [comment]
Windows Defender is turned off in Windows 10. In Windows 8, it does not have spyware properties.
