### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by metaxer** [Nummer/Destroy-Windows-10-Spying#164]
А как его обратно включить? 
хотел это сделать через Редактор групповой политики, но в компонентах Windows его нет =\

**Comment by metaxer** [comment]
разобрался как включить)

**Comment by Baigle** [comment]
"And how to turn back ?
I wanted to do it through the Group Policy Editor , but in the Windows components it is not = \

figured out how to turn on )
"

So its fixed? What was the solution?
Таким образом, это исправить? Что было решение ?
