### ISSUE TITLE
Сообщение о удалении шпионства даже если шпионских обновлений и сервисов не установлено

### ISSUE THREAD

**Issue by firefoxForUser** [Nummer/Destroy-Windows-10-Spying#167]
Когда запускаешь удаление сбора статистики, то программа пишет список удаляемого. Если такого шпионского сервиса нет, то она всёравно пишет об отключении. Хотело бы, чтобы она писала "сервиса не установлено" или другое сообщение о ошибке.

Например:

```
[INFO] Disabled task: Microsoft\Office\OfficeTelemetry\OfficeTelemetryAgentLogOn2016
```

у мен вообще никакого Office не установлено, а она получается что-то отключила? =)

**Comment by Nummer** [comment]
проверять наличие таска нету возможности, и программа отключает их, даже если их не существует. Это выполняет системная утилита)
