### ISSUE TITLE
Отображение опций не своей системы неактивными и с подпиской для какой системы

### ISSUE THREAD

**Issue by firefoxForUser** [Nummer/Destroy-Windows-10-Spying#169]
Отображение опций не своей системы неактивными и с подпиской для какой системы.

То есть если такого сервиса нету например на Win7, то всёравно отображать его, но неактивным и с подписью вконце: "для Win 10"

**Comment by Nummer** [comment]
в настройках это реализовано. Для Win7-8.1 нету разделений.
