### ISSUE TITLE
Не работает "Люди"(People)

### ISSUE THREAD

**Issue by Ramaska** [Nummer/Destroy-Windows-10-Spying#171]
После чистой установки Windows 10 pro 64bit rus (TH2 10.0.10586.3), и применение DWS_Lite версии 648, не запускается приложение "Люди"(People). все параметры программы по умолчанию + удалены метро приложения кроме Mail,Calendar, Maps и People, OneNote и Photos.(аналогичное поведение наблюдалось и в предыдущих версиях win 10 10240 + DWS)

**Comment by Nummer** [comment]
People отсылает информацию о ваших действиях. Оно отключается во время работы DWS
