### ISSUE TITLE
DWS and windows 10 Location gps

### ISSUE THREAD

**Issue by dienkhung** [Nummer/Destroy-Windows-10-Spying#172]
Hi, great program, I am running windows 10 pro, after I use this program, please tell me why my location button in action center is grayed out? Also in settings/privacy/location...windows will not allow me to change "location for this device is off" and "location on off button" because they are also grayed out. what option should I edit in host file in DWS lite should I change so that location gps will work? thank you for your help

**Comment by Nummer** [comment]
Information from the GPS server is sent to Microsoft. The purpose of DWS - turn it off.

**Comment by dienkhung** [comment]
Is there a way to just leave the GPS on? I use my device for maps a lot.
Everything else can be destroyed.
Thanks

**Comment by Nummer** [comment]
![image](https://cloud.githubusercontent.com/assets/7760838/11154818/ba0c56ec-8a52-11e5-96bb-6d6c21232e78.png)
change registry values.

**Comment by Nummer** [comment]
![image](https://cloud.githubusercontent.com/assets/7760838/11154835/c84168b0-8a52-11e5-85d3-ac09ee8e0d42.png)
and enable this values in registry

**Comment by dienkhung** [comment]
Thanks a lot, I really appreciate it
