### ISSUE TITLE
This completely broke my start menu, search and everything else!

### ISSUE THREAD

**Issue by Mrsevic** [Nummer/Destroy-Windows-10-Spying#174]
Thanks for nothing.

Now, fast startup is dead, bing is not working nothing is irreversible. I am not talking about start menu and search not working.

**Comment by Nummer** [comment]
turn on the search service. If this does not help, can not help, it is a reaction Cortana to block sending online queries.

**Comment by Mrsevic** [comment]
Really? So, you basically destroyed mine OS without even a proper notice. Start menu sometimes does not work, windows update is hanging... Better say this is an alpha because using this will result destroying your main OS not destroying the spying...

Why have not you told that this might happen on initial load of application?

**Comment by Mrsevic** [comment]
I cannot update to newest build also... Would you at least be so kind to tell me what have you changed regarding blocking the windows update? Jesus Christ

**Comment by infected-lp** [comment]
stop being a lame. if you dont know how to use software or what it will do to your system, DONT USE IT.

**Comment by Mrsevic** [comment]
Stop being irresponsible coder and pushing the system to the users without properly testing it first. I already used similar programs and I am pretty damn sure that result of an blocking should not be dead start menu and all other weird things that I somehow managed to fix caused by this software. 

You are lame not me.

**Comment by infected-lp** [comment]
you think you can do a better job?! good! get to work then!

**Comment by infected-lp** [comment]
i use this in every install i make of windows 10, never had issues.. so sorry mate, you are the lame here. end of discussion!

**Comment by infected-lp** [comment]
you dont even know how to do a simple reinstall of the fucking OS!!!! fucking noob.

**Comment by Mrsevic** [comment]
Listen to me very carefully you little worm. 

I have did trivial operation with this software and it caused ME a huge headache. I do not give a damn what it did to you. Second of all, I have did lots of OS installs and fixed various issues in coding generally.
There is no error with code here. It is just that authors have implemented functionality which ended up causing(I guess I am not alone) some users issues. 

When I write code  I first make sure that it is properly tested, that end users know what are the possible consequences. Run this software, every so often a new version comes.

And, fyi I have reinstalled the system and guess what? Another freaking error I never had with Win10.
0xC1900101 - 0x20004

So, I am not normally affiliated in this project I have installed it as I saw on the site that it removes some other M$ junk I never heard about. 

About your dictionary I do not want to discuss you're probably some kid who does not have elementary education? I admit that I am a little bit pissed off but I have good reason to do so.

**Comment by infected-lp** [comment]
lol... spoken like a true lame. take care!

**Comment by Mrsevic** [comment]
LOL. Lame is not a person. Brush up a little bit that English of yours you'll need it. Also, do not speak without arguments.

**Comment by infected-lp** [comment]
no shit dickwad... ! this is my last reply, and a kind one... GO FUCK YOURSELF, AND BUY A PLAYSTATION TO PLAY WITH, SINCE YOU ARE A ZERO AT PC'S.... fuck off kid .|.

**Comment by Mrsevic** [comment]
Hahhahah what a little pussy... Hahhahah.  Go walk with goats on the fields, you are not meant to do anything with coding and especially not to judge someone's level of knowledge. 

Zero at PC's. Hahahhah

**Comment by Draxler** [comment]
@Mrsevic 
You need to cool it off. You can't just come here and start acusing people and then expect to get a reply which could help you. It's open source project and you should know better how things work around here.

BTW: Both of you [ @infected-lp @Mrsevic ] need to delete all of these posts (crap) you posted out here and keep it civil.

**Comment by infected-lp** [comment]
done. and i will say again, if the user dont know even how to fix a windows 10 installation, he better off not using this tool, and blame the devs for screwing up his system... regards.

**Comment by Mrsevic** [comment]
I have just asked for the settings that utility might have changed in registry or God knows were so I can identify my problem. My approach was not good I admit. But calling someone lame without listening to his explanation is very inmature. Yet again I have tried reinstalling and I always get the0xC1900101 - 0x20004 and afterwards reverting to previous state error. I have looked in powershell logs for windows update as well as the logs for installation and I cannot identify the cause of the problem. It does not matter this will teach me to be carefull when it comes to modifying windows 10.

**Comment by Mrsevic** [comment]
I am not on Pc I will remove everything asap.

**Comment by Draxler** [comment]
@infected-lp 
Maybe so, but not all users are good at such things.  And i also think at least some suggestion (help) what to do  (to get PC back in earlier state at least) in case such as this, would be apropriate if big issues apears after installing some software.

cool, you both done step in right direction :)

**Comment by Draxler** [comment]
@Mrsevic

Some people find this software here eazy to use and realy good at what it does (you don't). 
Yet others like this one i posted here at the bottom better. It all depend what people like and what their skills are , in the end both of these softwares are realy good.  I suggest you try this one. But before you do, try to restore you PC on earlier time so you get all of your functions back. Hope you get it to work.

https://github.com/10se1ucgo/DisableWinTracking

Regards
