### ISSUE TITLE
CPU Core Temperature increase!

### ISSUE THREAD

**Issue by tangosdad** [Nummer/Destroy-Windows-10-Spying#177]
Why would running this program cause my CPU core temperatures to increase more than 20 degrees C? Before I ran this my idling temp was 35-36 C. After running this and rebooting numerous times, the idling temp is 57-58 C. I ran a system restore to a point prior to running DWS and now I'm back to 35-36 C. Any idea why such a big increase in temperature?

**Comment by vladios13** [comment]
Are you sure that this is due to the program? Maybe you have another program caused the load on the CPU?

**Comment by tangosdad** [comment]
There are no other programs running other than what is running after rebooting. I have left the machine idling for an hour each time and can duplicate this at will. System is in exactly the same state in each case except for the fact of having run DWS, or restoring to a point before DWS. It's as if there is a program that may be blocked from internet access and ends up spinning wildly in background. Now that part I don't have proof yet but will try to track it down further.

**Comment by Baigle** [comment]
you can use process explorer: https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx
part of a suite of amazing windows utilities: https://technet.microsoft.com/en-us/sysinternals/bb842062

using that you can go through settings and dig into whatever is causing the increased load, make sure to configure symbols if you look into a windows process' threads

quick keyboard shortcuts: CTRL + L brings up lower pane showing many interactions that selected process is using... go into settings to configure what you see throughout the program: highly recommended.

also, under settings make difference highlight duration 9 seconds from 1.. it helps a lot

it may also benefit you to rely on something other than windows defender if you are using this software that disables the "feature"

http://www.av-comparatives.org/dynamic-tests/

**Comment by marc011** [comment]
app for spooler system block firewall wer exe das host exe block ore removal microsofr feedback s/uf deployment manager client search a cortana aplication search ui disabled

**Comment by marc011** [comment]
BleachBit 1.8 secure removal tool cclean,er for remaining new apps removal sometimes other spyware apps added on u should encrypt google store entry
