### ISSUE TITLE
ability to remain Smart Screen functionality

### ISSUE THREAD

**Issue by nikolaymatveev** [Nummer/Destroy-Windows-10-Spying#180]
Thanks for your development!

Is there any ability to do that?
Smart Screen itself is working, but can't connect to server.

What hosts are provide such service? Are them provide only Smart Screen functionality?

![untitled](https://cloud.githubusercontent.com/assets/15851650/11168102/0f299a5a-8b92-11e5-9e44-853193eec9d2.png)

**Comment by marc011** [comment]
app for spooler system block firewall wer exe block ore removal
