### ISSUE TITLE
Отключение автоповорота

### ISSUE THREAD

**Issue by nrainx** [Nummer/Destroy-Windows-10-Spying#182]
После установки на планшете (Lenova Yoga 2 tablet 10) слитает автоповорот, датчик орентации вообще пропадает

**Comment by Nummer** [comment]
Хм. Данная проблема остаётся актуальной. Но думаю разрешать M$ получать геолокацию, и некоторые другие данные - плохая идея. Напишите мне на почту admin@nummerdev.ru ваш скайп. Я добавлю вас, и мы решим проблему с вашим планшетом не затрагивая шпионство. Мне нужен будет удалённый доступ.

**Comment by acer011** [comment]
все же может предложите решение автоповорота ? многие ищут проблему :(

**Comment by Nummer** [comment]
https://github.com/Nummer/Destroy-Windows-10-Spying/issues/219

**Comment by acer011** [comment]
219 пост не решает проблему сервис не хочет запускаться :(

**Comment by Nummer** [comment]
@acer011 в новом DWS есть фикс данной проблемы. После фикса перезагрузите компьютер
