### ISSUE TITLE
Cortana disabled

### ISSUE THREAD

**Issue by ghost1372** [Nummer/Destroy-Windows-10-Spying#183]
Hello
After launching the application and clicking on the " Destroy windows 10 spying " Cortana is not working.
The following message displays
cortana is disabled by company policy.
how i can fix it?i need cortana.

**Comment by Nummer** [comment]
Soon to be added to roll back changes.

**Comment by marc011** [comment]
app for spooler system block firewall  wer exe block ore removal

**Comment by thechawals** [comment]
What the hell is that i use this tool and now facing this frustrating issue..Fix it fast

**Comment by thechawals** [comment]
If you cant update your programme then tell me an easy and manual way..

**Comment by miglos** [comment]
you can reactvate cortana in grouppolicies

**Comment by SeeYoo** [comment]
You can change the value of "AllowCortana" from 0 to 1 in this path (in the registry): HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Search

This will bring back Cortana.

**Comment by KiUserExceptionDispatcher** [comment]
Are you sure Cortana don't spying on you?

**Comment by ShayBox** [comment]
That regedit value doesn't exist anymore.
