### ISSUE TITLE
After last update i can't use fingerprint-login anymore

### ISSUE THREAD

**Issue by eugenenv** [Nummer/Destroy-Windows-10-Spying#184]
As title says, i can't point on specific release, but i can't login via fingerprint-reader anymore (maybe cause windows hello blocking?)

**Comment by Nummer** [comment]
DWS disables this feature.

**Comment by eugenenv** [comment]
Well, how can i re-enable it?

**Comment by marc011** [comment]
app for spooler system block firewall wer exe das host exe  block ore removal microsofr feedback s/uf deployment manager client  search a cortana aplication
