### ISSUE TITLE
Torrent-Updates

### ISSUE THREAD

**Issue by Ch4rg3r** [Nummer/Destroy-Windows-10-Spying#185]
Would be nice, if DWS disables this function of Windows update. Or change it to local network only.

**Comment by Nummer** [comment]
add

**Comment by Ch4rg3r** [comment]
Found this one explainig how to disable torrent-updates by Registry editing [here](https://techjourney.net/enable-or-disable-peer-to-peer-p2p-apps-updates-download-from-more-than-one-place-in-windows-10/). 

>Windows 10 P2P delivery method is handled by Delivery Optimization (DoSvr) service. The settings for Delivery Optimization is stored in the registry key below, allowing manipulation via Group Policy (GPO) through script:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Config

>REG_DWORD Value: DODownloadMode

>Possible value date:

>0 = Off
>1 = On, PCs on my local network
>3 = On, PCs on my local network, and PCs on the Internet

The 'DWORD DODownloadMode' seems to be unknows, as it says two different possible values (see above and following from [here](http://windowsitpro.com/windows-10/managing-windows-10s-new-peer-updating-capability-using-gpo))

>Data: 0 = off; 2 = PCs on my local network; 3 = PCs on my local network, and PCs on the Internet
