### ISSUE TITLE
cpu load increases/ windows reinstall the updates again when restarting the computer

### ISSUE THREAD

**Issue by amback** [Nummer/Destroy-Windows-10-Spying#188]
guys i am not quite sure what to do anymore, to begin each time i run the program and remove the updates my cpu load increases dramatically and so does the temperature, specifically this process
![nsa](https://cloud.githubusercontent.com/assets/13859603/11186907/0754fc50-8c52-11e5-9e7a-3c9f7edc8e56.PNG)

my other problem is as soon i restart the computer windows installs the updates again, any help would truly be appreciated, how do i complele delete this updates from my computer?
also when running the program i get a message at the end saying "GWX NOT FOUND" can this part of the issue?
![nsa2](https://cloud.githubusercontent.com/assets/13859603/11187035/ace4784e-8c52-11e5-85b6-a9f4a2fac26a.PNG)

**Comment by Nummer** [comment]
fixed in new version

**Comment by marc011** [comment]
app for spooler system block firewall wer exe block ore removal
