### ISSUE TITLE
A bug report

### ISSUE THREAD

**Issue by driverchoo** [Nummer/Destroy-Windows-10-Spying#190]
When I used the last DWS ot my Win7 SP1 x64, it disabled the windows explorer FTP access. Now I cant use my network FTP server and have to install an externa program.

**Comment by driverchoo** [comment]
The last working build is 600. After that, all newer wersions bugs windows explorer. Sometimes it hags and the ftp options are not working.

**Comment by Nummer** [comment]
Sorry, but explorer.exe sends information about the files on the server by Microsoft, and it was denied access to the network.

Look firewall

**Comment by marc011** [comment]
app for spooler system block firewall wer exe das host exe  block ore removal microsofr feedback s/uf deployment manager client  search a cortana aplication
