### ISSUE TITLE
error windows update

### ISSUE THREAD

**Issue by setmos** [Nummer/Destroy-Windows-10-Spying#192]
buenas desde que use su programa no puedo instalar nada de la tienda de apps de windos 10 y tampoco me llegan las actualzaciones de windows incluida threeshold 2 

he probado con todo, incluso la opcion enable windows update pero nada funciona

su programa ha estropeado mi windows y espero que me den una solucion tecnica para revertir los cambios. hevuelto a un punto de restauracion anterior y nada funciona. 

espero y confio en su respuesta

gracias

**Comment by Nummer** [comment]
Windows Store - Spying app.

**Comment by marc011** [comment]
app for spooler system block firewall wer exe das host exe  block ore removal microsofr feedback s/uf deployment manager client  search a cortana aplication

**Comment by setmos** [comment]
Trash app


Samuel Ortega 



En 18 de nov. de 2015 16:13, en 16:13, marc011 <notifications@github.com> escrito:

**Comment by marc011** [comment]
Registersleutel verwijderen 0 HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\UserAssist\{CEBFF5CD-ACE2-4F4F-9178-9926F41749EA}\Count
Registersleutel verwijderen 0 HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\UserAssist\{F4E57C4B-2036-45F0-A9AB-443BCFE33D9F}\Count
Registersleutel verwijderen 0 HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\RecentDocs
Verwijderen 2.6kB C:\Users\user\AppData\Roaming\Microsoft\Windows\Recent\AutomaticDestinations\5f7b5f1e01b83767.automaticDestinations-ms
Verwijderen 6.1kB C:\Users\user\AppData\Roaming\Microsoft\Windows\Recent\AutomaticDestinations\f01b4d95cf55d32a.automaticDestinations-ms
Verwijderen 6.2kB C:\Users\user\AppData\Roaming\Microsoft\Windows\Recent\CustomDestinations\590aee7bdd69b59b.customDestinations-ms
Verwijderen 5.5kB C:\Users\user\AppData\Roaming\Microsoft\Windows\Recent\CustomDestinations\969252ce11249fdd.customDestinations-ms
Verwijderen 9.1kB C:\Users\user\AppData\Roaming\Microsoft\Windows\Recent\CustomDestinations\c21386f4d2fb73ce.customDestinations-ms
Verwijderen 864B C:\Users\user\AppData\Local\Mozilla\Firefox\Profiles\q2dqt6nl.default\cache2\entries\0448BF2CA385066388F48E52BCD9B761D2876A67
Verwijderen 2kB C:\Users\user\AppData\Local\Mozilla\Firefox\Profiles\q2dqt6nl.default\cache2\entries\08F5545BBA5F4F270CAF780EC40DCA9168B8D435
Verwijderen 900B C:\Users\user\AppData\Local\Mozilla\Firefox\Profiles\q2dqt6nl.default\cache2\entries\29013309A7001508E025A9CEF743004743D1BC5E
Verwijderen 864B C:\Users\user\AppData\Local\Mozilla\Firefox\Profiles\q2dqt6nl.default\cache2\entries\57DFBBE26B60759B3E6D4EC6F73BB28D2FCE0033
Verwijderen 900B C:\Users\user\AppData\Local\Mozilla\Firefox\Profiles\q2dqt6nl.default\cache2\entries\C0AAE8C613FCCD4DC7B1DC8A12D43DC9D06DE19E
Verwijderen 2.2kB C:\Users\user\AppData\Local\Mozilla\Firefox\Profiles\q2dqt6nl.default\cache2\entries\D6E04376418D479E7DC26AAD5D24953D729D91E4
Verwijderen 864B C:\Users\user\AppData\Local\Mozilla\Firefox\Profiles\q2dqt6nl.default\cache2\entries\F0CD1D8AF7C3DBFD777DDECBF9EEA8BE69767042
Verwijderen 524.3kB C:\Users\user\Application Data\Mozilla\Firefox\Profiles\q2dqt6nl.default\cookies.sqlite
Verwijderen 10B C:\Users\user\Application Data\Mozilla\Firefox\Crash Reports\InstallTime20151029151421
Verwijderen 98.3kB C:\Users\user\Application Data\Mozilla\Firefox\Profiles\q2dqt6nl.default\webappsstore.sqlite
Verwijderen 196.6kB C:\Users\user\Application Data\Mozilla\Firefox\Profiles\q2dqt6nl.default\formhistory.sqlite
Optimaliseren 0 C:\Users\user\Application Data\Mozilla\Firefox\Profiles\q2dqt6nl.default\content-prefs.sqlite
Optimaliseren 0 C:\Users\user\Application Data\Mozilla\Firefox\Profiles\q2dqt6nl.default\healthreport.sqlite
Optimaliseren 0 C:\Users\user\Application Data\Mozilla\Firefox\Profiles\q2dqt6nl.default\permissions.sqlite
Optimaliseren 0 C:\Users\user\Application Data\Mozilla\Firefox\Profiles\q2dqt6nl.default\places.sqlite
Verwijderen 229.4kB C:\Users\user\Application Data\Mozilla\Firefox\Profiles\q2dqt6nl.default\content-prefs.sqlite
Verwijder de gebruikersgeschiedenis 0 C:\Users\user\Application Data\Mozilla\Firefox\Profiles\q2dqt6nl.default\places.sqlite
Verwijderen 0 C:\Users\user\AppData\Roaming\Adobe\Flash Player\AssetCache\NRB2M6ZY
Verwijderen 0 C:\Users\user\AppData\Roaming\Adobe\Flash Player\NativeCache\NativeCache.directory
Verwijderen 0 C:\Users\user\AppData\Roaming\Macromedia\Flash Player\#SharedObjects\C5YSKCZL
Verwijderen 492B C:\Users\user\AppData\Roaming\Macromedia\Flash Player\macromedia.com\support\flashplayer\sys\settings.sol
Klembord 0 
Registersleutel verwijderen 0 HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache
net stop wuauserv 0 
net start wuauserv 0 
Verwijderen 0 C:\Users\user\Local Settings\Temp\acro_rd_dir
Verwijderen 0 C:\Users\user\AppData\Local\Microsoft\Windows\History\History.IE5\container.dat
Verwijderen 20.1kB C:\Users\user\AppData\Local\NVIDIA\NvBackend\backend.log.bak
Verwijderen 93.9kB C:\Users\user\AppData\Local\NVIDIA\NvBackend\journalBS.jour.dat.bak
Verwijderen 23.5kB C:\Users\user\AppData\Local\NVIDIA\NvBackend\journalBS.main.xml.bak

verwijderen )- remove comand
