### ISSUE TITLE
automatic display rotation

### ISSUE THREAD

**Issue by Pegas1606** [Nummer/Destroy-Windows-10-Spying#193]
I do not know what happened, but after using DWS tablet I stopped going automatic display rotation. Does anyone know what this is? I have Windows 10 the new build. It did not work even when using a restore point. I had to use restoring to factory settings and then it went normally.I do not know how much English so I apologize in advance that I used a translator from Google.

**Comment by Nummer** [comment]
https://github.com/Nummer/Destroy-Windows-10-Spying/issues/182
