### ISSUE TITLE
program killed windows networking

### ISSUE THREAD

**Issue by tovarnadoma** [Nummer/Destroy-Windows-10-Spying#195]
internet is still working, but windows update and EDGE browser and tools like DISM.EXE etc dont see it... 

also network tray icon is gone, and my network connection is now public, not private/home as it was before.

Would like to get windows update back, but no luck.

when i went into properties of task bar and clicked on nofitication area "customization", and "turn system icons on/off" but the network icon is completely grayed out...  no option to enable it :\

i used latest dws lite 693.

--  btw, i tried clicking the "enable windows update" but no change, even after reboot...

**Comment by Nummer** [comment]
not a bug
