### ISSUE TITLE
please add to hosts

### ISSUE THREAD

**Issue by CNMan** [Nummer/Destroy-Windows-10-Spying#196]
settings-win.data.microsoft.com
v10.vortex-win.data.microsoft.com
win10.ipv6.microsoft.com
dmd.metaservices.microsoft.com
dns.msftncsi.com

Do not have A record:
adnexus.net
adnxs.com
ca.telemetry.microsoft.com
i1.services.social.microsoft.com.nsatc.net
deploy.static.akamaitechnologies.com
akamaitechnologies.com

CNAME is useless
fe3.delivery.dsp.mp.microsoft.com.nsatc.net should be fe3.delivery.mp.microsoft.com
*.microsoft.com.nsatc.net should be deleted

**Comment by Nummer** [comment]
thx

**Comment by Nummer** [comment]
add
