### ISSUE TITLE
Wrong or harmful hosts  values

### ISSUE THREAD

**Issue by F03SD** [Nummer/Destroy-Windows-10-Spying#197]
[INFO] Add to hosts - deploy.static.akamaitechnologies.com
[INFO] Add to hosts - akamaitechnologies.com
Akamai Technologies, Inc. is a content delivery network or CDN and cloud services.
the company's customers:  Adobe, Apple, AMD, Amazon.com, Autodesk, BBC, BenQ, Blizzard, CNET, European Space Agency, Facebook, IBM, GitHub, L’Oréal, Microsoft, MySpace, NASA, Nintendo, NVIDIA, PC World, Sony, Symantec, Red Hat, Reuters, Siemens, RingCentral, Yahoo, Valve, Buzzfeed,Youtube and e.t.c.
-----------------------------------------------------------------------------------------
 spynet2.microsoft.com 
 spynetalt.microsoft.com 

Ussles here , this addreses is fake.

Domian: spynetalt.microsoft.com 
Server Name: MICROSOFT.COM.ARE.GODDAMN.PIGFUCKERS.NET.NS-NOT-IN-SERVICE.COM
   IP Address: 216.127.80.46
   Registrar: TUCOWS DOMAINS INC.
   Whois Server: whois.tucows.com
   Referral URL: http://www.tucowsdomains.com

   Server Name: MICROSOFT.COM.CAN.GO.FUCK.ITSELF.AT.SECZY.COM
   IP Address: 209.187.114.147
   Registrar: TUCOWS DOMAINS INC.
   Whois Server: whois.tucows.com

**Comment by Nummer** [comment]
fixed

**Comment by Jedihoth** [comment]
I dont understand what the hell are you saying, is it kinda of a joke? Can you explain for straight thinkers? Stop these crooked snaky cranky cranks
