### ISSUE TITLE
[suggestion] add status display for tweaks

### ISSUE THREAD

**Issue by stasuss** [Nummer/Destroy-Windows-10-Spying#2]
display the status for those tweaks, e.g. are there active spy tasks, or enabled spy services, so after updates you can run this programm and see if you need to re-run procedure.

показывать статус для твиков, например активные шпионские задания или службы, так что после обновлений можно запустить программку и увидеть нужно ли заново проводить лечение.

**Comment by Nummer** [comment]
add display UAC
