### ISSUE TITLE
blackdoor 

### ISSUE THREAD

**Issue by gab12** [Nummer/Destroy-Windows-10-Spying#202]
Hi,

DWS install a new certificat. Can you explain why ?
Because it's an important blackdoor and security breach to install a new certificat.
DWs is very Dangerous. is it a Russian product ?

**Comment by zeffy** [comment]
I was also wondering about this. Installing that WZT certificate as a root cert is a huge security risk for users. I wouldn't recommend using DWS in its current state due to this "feature".

**Comment by dartraiden** [comment]
@gab12. http://i73.fastpic.ru/big/2015/1126/e4/8bc8b9d3e794a62e4fa2695aea2b5be4.jpg
english: that no one could make a a fake version of this program


author has no money to buy certificate, so he uses a self-signed, and adds it to the root
it is very bad and reckless practice

**Comment by zeffy** [comment]
I agree, that's not even a valid reason. The same thing could be accomplished by providing SHA-1 hashes to verify file integrity.

**Comment by Nummer** [comment]
@zeffy th2 removes DWS if it is not signed by a certificate. The certificate is required for this.

**Comment by zeffy** [comment]
@Nummer does it really, though? I'm using TH2 and can run DWS unsigned just fine, but whatever.

**Comment by Nummer** [comment]
@zeffy Microsoft has removed unsigned software from your computer. This will continue. DWS need a life.

**Comment by zeffy** [comment]
@Nummer they most certainly do not, but I'm obviously not going to change your mind, so let's just agree to disagree.

**Comment by vith** [comment]
Removed in 7e715ff, just to save anyone else having to search through the commits.

Maybe there should be warnings and instructions to remove the cert?

If I'm understanding correctly, this was the same thing as [Superfish](http://arstechnica.com/security/2015/02/lenovo-pcs-ship-with-man-in-the-middle-adware-that-breaks-https-connections/) and [eDellRoot](http://arstechnica.com/security/2015/11/dell-does-superfish-ships-pcs-with-self-signed-root-certificates/)?

**Comment by zeffy** [comment]
@vith To remove a previously installed WZT certificate, press Win+R and run `certlm.msc`, then navigate to **Trusted Publishers > Certificates** and **Trusted Root Certificate Authorities > Certificates** and delete the WZT entries.

And yes, this opened systems to the same vulnerabilities as Superfish and eDellRoot except for that only people in possession of the WZT cert's private key would be able to initiate MITM attacks on users.
