### ISSUE TITLE
KB désinstallées par destroy

### ISSUE THREAD

**Issue by webab** [Nummer/Destroy-Windows-10-Spying#205]
bonjour

sous windows 7 et 8.1
destroy-windows Spying 
propose la désinstallation de deux mise a jour , qui n'on rien a voir 
avec la télémétrie ou la préparation au passage a  windows 10
ces deux mises a jour sont des mises a jour de sécurité a ne pas désinstaller !
il serait souhaitable qu'elles soit retirées de la liste de mise a jour a désinstaller !
KB 3088195
KB 3042058

**Comment by Nummer** [comment]
this spying update
