### ISSUE TITLE
DWS (Blacklist update + Greek Language)

### ISSUE THREAD

**Issue by GrayHatSecurity** [Nummer/Destroy-Windows-10-Spying#208]
Mr Nummer, i am a big fan of your work on DWS project.
I read your code which is perfect and i added more windows updates (from my blacklist :P ).
Also i can write a Greek translation if you are interested, just send me an OK.

contact me in grayhatsec@protonmail.ch
Greeting from Greece, Putin RULEZ :)

**Comment by Nummer** [comment]
create pull request
