### ISSUE TITLE
My windows 10 is falling

### ISSUE THREAD

**Issue by onilink90** [Nummer/Destroy-Windows-10-Spying#21]
I dont have the protection of windows defender , the restart point is deleted and I cant rollback the cahnges did the program I have the dws lite 1.5 build 302 please How can I do???? I dont want to re install al of my system please help me!!

**Comment by MrYadro** [comment]
Same thing. Half of settings are blocked, update unavailable, system restore point wasn't created.

**Comment by Nummer** [comment]
Think head and check the settings before using the program.
At the moment, there is no rollback.

**Comment by MrYadro** [comment]
10 / 10

**Comment by onilink90** [comment]
I erase the lines in the hosts file and then enter to gpedit.msc and turn on the windows defender and windows update so then today all my fixes I think be supported by microsoft automatically :smiley:
