### ISSUE TITLE
some app taskbar icons disappear after using dws

### ISSUE THREAD

**Issue by matt-derrick** [Nummer/Destroy-Windows-10-Spying#210]
Directly after using this program some (but not all) of my application taskbar icons have disappeared, and I can't seem to get them to come back. Not a huge deal, but kinda annoying when you have multiple apps open and can't tell which is which.

they all seem to be replaced with some kind of generic painting icon (see screenshot).

<img width="386" alt="example" src="https://cloud.githubusercontent.com/assets/5995343/11483078/5a69693a-975b-11e5-96e9-da27d3df383a.png">

**Comment by matt-derrick** [comment]
for reference, that app is evernote.

**Comment by Nummer** [comment]
this is windows 10 bug

**Comment by matt-derrick** [comment]
how can you say that's a 'windows 10 bug' when it **only** happens after using this software?
