### ISSUE TITLE
Чем не угодили KB3042058 и KB3088195 под Win7?

### ISSUE THREAD

**Issue by ache** [Nummer/Destroy-Windows-10-Spying#211]
Во-первых, судя по описаниям, они нужны.
Во-вторых если снести KB3042058, KB3080079 (не в списке) ставится с ошибкой 0x80070490.

**Comment by useribs** [comment]
+1. Ошибка вроде, но как-то с исправлением не очень пока. https://github.com/Nummer/Destroy-Windows-10-Spying/issues/151#issuecomment-156627640

**Comment by Nummer** [comment]
они включают в себя патчи по фиксу телеметрии.

**Comment by ache** [comment]
Так проще её давить через GP/Registry, как в 10, чем мешать security апдейтам, после которых не ставятся другие security апдейты.

**Comment by Nummer** [comment]
ну в этом вы немного правы, но я думаю что надёжнее будет вырезать это обновление. Если вы не желаете его удалять, то можете в любой момент отключить удаление данного обновления
