### ISSUE TITLE
Добавить список вредных обновлений с описанием

### ISSUE THREAD

**Issue by firefoxForUser** [Nummer/Destroy-Windows-10-Spying#220]
Предлагаю сделать отдельный репозиторий и создать там список вредных обновлений и функций с описанием. Туда же добавить команды для cmd для их отключения.
То есть сделать нечто вроде блога, возможно открыть Wiki на GitHUB.

По моему это позволит быстрее отслеживать появление новых вредных обновлений и функций. Пользователи пусть кидают туда найденное в Issues.
Написать тут в README чтобы шли туда с такими вопросами.

Создать каталог всего вредного в общем.

Туда же ссылаться в справке программы.

**Comment by Nummer** [comment]
wiki.
TODO: ADD
