### ISSUE TITLE
Нарушение лицензии Microsoft?

### ISSUE THREAD

**Issue by firefoxForUser** [Nummer/Destroy-Windows-10-Spying#221]
Ходят слухи, что действия этой программы могут нарушать лицензию.
Поэтому предлагаю разделить программу на ядро, которое исполняет команды и рисует интерфейс. И сам список команд.

Для списка команд сделать отдельный репозиторий. Например хранить там .properties файл, который пополнять по мере необходимости.

**Comment by Nummer** [comment]
Действия данной программы нарушают лицензионное соглашение Microsoft. Вы пользуетесь ей на свой страх и риск (если вы в организации)
