### ISSUE TITLE
Предлагаю обсудить, что позволяет отключать в плане шпионства новое обновление Windows

### ISSUE THREAD

**Issue by firefoxForUser** [Nummer/Destroy-Windows-10-Spying#222]
Подробнее тут http://habrahabr.ru/company/edison/blog/272591/

Распространяется это на Win7 и Win8? Или только для Win10? Всё ли отключается?
Вообще это хорошие новости, так как Win7-10 Enterprise можно свободно скачать с сайта MS. Там пробник на пол года.

**Comment by Nummer** [comment]
лабуда это.
