### ISSUE TITLE
skype bug

### ISSUE THREAD

**Issue by adrianyujs** [Nummer/Destroy-Windows-10-Spying#235]
after use this, its block access to download update, even worst it block the skype website.

But the application itself like normal, can online and chat with friend. ONLY not able to download update and access the website.

EDIT:

I found out that this firewall rule "111.221.64.0-111.221.127.255_Block" blocked access to it. And I disabled the rule and voila no issue.

I checked nslookup to skype website their IP is below

Name:    www.skype.akadns.net
Address:  111.221.123.232
Aliases:  www.skype.com

So next version will remove the rule?

**Comment by winap2** [comment]
I have no problem with skype update..(release 716)

**Comment by adrianyujs** [comment]
Den I think its country dependent.

**Comment by Nummer** [comment]
DWS has nothing to do with it.

**Comment by adrianyujs** [comment]
DWS add this list in "111.221.64.0-111.221.127.255_Block"

which block access to skype website.

**Comment by fuerzaaa** [comment]
unlock in brandmayer and host-64.4.23.0-64.4.23.255 and Skype will work
