### ISSUE TITLE
Windows Search and Indexing

### ISSUE THREAD

**Issue by Foshitz** [Nummer/Destroy-Windows-10-Spying#238]
This application totally screwed up my Windows Search and Search Indexing.
I can´t restart the Windows Search service due to error message "Error 3: The system could not find the path specified".
I tried to reactivate the feature under "Turn Windows features on or off" but Windows Search is missing from that list.
I also ran the "System file check (SFC) Scan" which found corrupted files, but even though the scan was able to repair all issues I still can't restart the service or activate the feature.

**Comment by SeriousM** [comment]
I know that doesn't fix the problem, but you can use the Tool "Everything" from VoidTools: https://www.voidtools.com/

It's much faster and doesn't suck performance like Windows Search Index.

**Comment by leannecrow** [comment]
Everything is awesome but Indexing actually goes into the data content instead of just the header.
