### ISSUE TITLE
Can't use built-in recovery options.

### ISSUE THREAD

**Issue by Foshitz** [Nummer/Destroy-Windows-10-Spying#239]
Besides my other two issues (#237 & #238), now i´m not even able to refresh or restore my Windows 10 installation, because your program corrupted my "winload.exe"
See screenshot, and fix your software!

![dsc_0042](https://cloud.githubusercontent.com/assets/16353951/11913605/8033ddcc-a669-11e5-991b-80d16d0df682.JPG)

**Comment by Nummer** [comment]
=\
DWS has nothing to do with it.
