### ISSUE TITLE
Genuine KB

### ISSUE THREAD

**Issue by winap2** [Nummer/Destroy-Windows-10-Spying#240]
Hi there is new KB article KB3109094 to find crack or genuine windows. 
If the windows are genuine, KB still identification this copy is not genuine. 
Please paste this KB into uninstall option, thanks.

**Comment by Matthi3u** [comment]
It's an update for Vista/2008 https://www.microsoft.com/en-us/download/details.aspx?id=50327

**Comment by winap2** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=50311
Not only Vista :) They offers a security patch, but it´s "hoax", it´t not security hottfix.
