### ISSUE TITLE
Ayudenme Por favor

### ISSUE THREAD

**Issue by guayakos** [Nummer/Destroy-Windows-10-Spying#241]
Agradezco por su amable tiempo y dedicación al programa

Tengo un incoveniente con UTORRENT no me permite descargar nada desde que instale el destroy win10; les rogaría que me ayuden con este problema...

Mil gracias

**Comment by guayakos** [comment]
![01](https://cloud.githubusercontent.com/assets/16364399/11914636/bfa25ad0-a653-11e5-9389-0b8a3e73b4a2.png)

**Comment by guayakos** [comment]
No es posible por ningun medio realizar ninguna descarga...

**Comment by Nummer** [comment]
DWS has nothing to do with it.

**Comment by guayakos** [comment]
Thks for the time...


2015-12-20 2:54 GMT-05:00 Nummer <notifications@github.com>:

**Comment by LestatAb** [comment]
Deshabilita el firewall y comprueba si puedes realizar descargas. Después de instalar DWS no podia conectarme a algunos juegos que comparten ips con microsoft, deshabilitando el firewall lograba conectarme y comentando las modificaciones del archivo host.
