### ISSUE TITLE
4 Removed Windows 8.1 Updates Return - Presumably Not Successfully Hidden

### ISSUE THREAD

**Issue by ghost** [Nummer/Destroy-Windows-10-Spying#247]
DWS Lite attempts to 'hide' the Windows updates it removes but in Windows 8.1 (two independent installations of Windows 8.1 so far) the following updates reappear for reinstallation afterwards:
KB3042058
KB3088195
KB3044374
KB3112336

**Comment by Nummer** [comment]
=\
