### ISSUE TITLE
Static routes don't work

### ISSUE THREAD

**Issue by Sloven0** [Nummer/Destroy-Windows-10-Spying#248]
To additionsl block microsoft streams the programm add dozents static routes without interface, without gateway (on-link) like 
route -p add 65.52.100.94 mask 255.255.255.255 0.0.0.0
It works fine. Packets drop. But after system reboot this routes come out from active and doesn't work. Trace showes that streams go to default gateway.
To prevent this behavior I think is need to add loopback interface to all routes like
route -p change 65.52.100.94 mask 255.255.255.255 0.0.0.0 if 1

**Comment by Sloven0** [comment]
exact the same issue https://social.technet.microsoft.com/Forums/windows/en-US/58cbac62-dd43-4913-8096-81810eb1d572/windows-2008-r2-persistent-routes-are-ignored-after-reboot?forum=winserverPN
Somehow windows doesnt determine any interface. Suggest to use if

**Comment by Nummer** [comment]
add
