### ISSUE TITLE
feature suggestion: MVPs hosts file

### ISSUE THREAD

**Issue by NetworkPro** [Nummer/Destroy-Windows-10-Spying#25]
I suggest a new feature with a separate button - to apply mvps shosts file to filter out connections to adware that are made by some installers such as open candy servers etc

would be nice to have detection of updated mvps hosts file so we know if a new one has been published and if we need to update in our hosts

will also filter many ads on websites

**Comment by Nummer** [comment]
The program removes spying, but does not disable advertising.
