### ISSUE TITLE
Cannot install apps from the store after using last version Destroy Windows 10 Spying. Code error: 0x80240438.

### ISSUE THREAD

**Issue by trex20** [Nummer/Destroy-Windows-10-Spying#251]
Cannot install apps from the store after using last version Destroy Windows 10 Spying. Code error: 0x80240438.
It's really annoing, I reinstalled Windows for that, until I found from where the problem is.

**Comment by Nummer** [comment]
dws removed windows store.

**Comment by Nummer** [comment]
don't add hosts and firewall rules.
