### ISSUE TITLE
Trojan-Spy.MSIL.Keylogger.cgdz

### ISSUE THREAD

**Issue by nasasss** [Nummer/Destroy-Windows-10-Spying#264]
DNS requests
VBOXSVR.ovh.net
 UDP communications
<MACHINE_DNS_SERVER>:53

https://www.virustotal.com/en/file/032d394fd6884a275b8a24dc5dbba3bbcd605c7958f7b2e4c6843e999d7292bd/analysis/1471567164/

**Comment by Nummer** [comment]
duplicate https://github.com/Nummer/Destroy-Windows-10-Spying/issues/263
