### ISSUE TITLE
Fingerprint not working

### ISSUE THREAD

**Issue by LestatAb** [Nummer/Destroy-Windows-10-Spying#266]
I used the program for months on Several computers and I have not HAD any problems. I recently buyed a HP Laptop with Fingerprint and after install DWS i try login with fingerprint and not work. I open the HP Client Security program and try to register the finger the next message Appear: The fingerprint reader Not Connected. Connect the reader.
This happen before and after to update Windows 10 anniversary and i dont disable windows defender option.

**Comment by gable44** [comment]
Hello Guys!

I experienced something similar, after using the DWS the fingerprint readers setting are disabled and can to be reactivated.

**Comment by LestatAb** [comment]
After format, the fingerprint works well, and after apply DWS i get the same issue.

**Comment by xaricx** [comment]
I've had luck by manually starting the Windows Biometric service and setting it to Autostart.

**Comment by Xanarkan** [comment]
Look here for the solution to your issue: [https://github.com/Nummer/Destroy-Windows-10-Spying/issues/283](url)

**Comment by eaglespeed** [comment]
> I've had luck by manually starting the Windows Biometric service and setting it to Autostart.

thank you very much this worked for me as well I really didn't want to reinstall windows 10. I tried everything but this seem to do the trick. cheers.
