### ISSUE TITLE
Windows Defender detects the .exe file as Malicious

### ISSUE THREAD

**Issue by GalaxyLJGD** [Nummer/Destroy-Windows-10-Spying#268]
**Windows Defender** made an automatic analysis and detected **DWS_Lite.exe** as a Trojan, saying this _TrojanSpy:Win32/Skeeyah.A!rfn_.

The version that I downloaded as the page was the _2016-08-18T08: 44:16Z_.

I leave a picture of how appears me if it is useful

![Windows Defender](https://cloud.githubusercontent.com/assets/11948239/18102906/6a389dce-6ec2-11e6-8b84-ff57164a086d.png)

PD: Sorry for my bad English.

**Comment by BlackRouter** [comment]
You can See Sources on Github and check for No malicious code.
Microsoft To prevent Change on Some telemetry , Windows defender detect TrojanSpy.

**Comment by DarkKnight64** [comment]
It's probably detected as Spyware due to the obtrusive telemetry destruction, Metro app removal, etc.

**Comment by Wohlstand** [comment]
That means: Microsoft knows that people are trying that people killing their spy machine
