### ISSUE TITLE
Make an option available to ALLOW installation of apps from the Store.

### ISSUE THREAD

**Issue by bmferreira** [Nummer/Destroy-Windows-10-Spying#274]
After applying Destroy Windows 10 Spying on 2 computers I am not able to download apps from the Store. Make an option available (checkbox) to enable or disable store apps installation/download.

**Comment by filin0v0** [comment]
Turn of Rule "191.232.139.2_Block" in windows firewall.

**Comment by dubsector** [comment]
@filin0v0 Tried that and still keep getting the same error.

![2017-01-25_13-58-04](https://cloud.githubusercontent.com/assets/4384205/22304723/a015ddae-e306-11e6-8b02-85e8497ab903.png)

**Comment by Wohlstand** [comment]
Another case: if Windows isn't patched, it won't able to download DWS (from github, but successfully from copy pasta on my server), not only by Edge: by any browser include Firefox, but successfully downloading from same machine under Linux in same Firefox

**Comment by filin0v0** [comment]
Tyr to reboot.
or try turn of "191.232.139.254_Block".
