### ISSUE TITLE
Skype issues

### ISSUE THREAD

**Issue by ItsCEED** [Nummer/Destroy-Windows-10-Spying#275]
After using the tool, i cant access skype.

I guess its blocked hosts, which hosts should i remove so i can gain access to skype

It is fresh OS install, and skype was working fine before i use DWS

**Comment by psimona** [comment]
Same issue over here. Disabled all the DNS redirection in the windows hosts file (C:\Windows\System32\drivers\etc) and skype works.

Removing the entries *.skype.com does not suffice.

If I have more information I will post.
Cheers

**Comment by 1337-537h** [comment]
Same problem here. Trying to solve it.

**Comment by masterberg-br** [comment]
I tried running wireshark to see which ips are being used on the calls, but its a messy list of too many connections.
Btw, maybe we should update and organize what each adress means every IP. Will be better for new issues.

**Comment by valeriy-egorov** [comment]
remove:
s.gateway.messenger.live.com

**Comment by psimona** [comment]
Only removing s.gateway.messenger.live.com does not work for me. It logs in but it never goes online, the spinning blue wheel stays there.

For testing be sure to empty the dns cache and the skype temp files. You can do this with the following Powershell oneliner (WARING DESTRUCTIVE OPERATION - THIS DELETES THE SKYPE CONFIGURATION)

`rm -Recurse -Force $env:APPDATA\Skype\* ; ipconfig /flushdns ; Skype.exe`

This one only flushes the dns cache

`ipconfig /flushdns`

Also I noticed that if you log in many times the authentication servers will lock you out for a while making any login fail.

**Comment by valeriy-egorov** [comment]
try-
# 0.0.0.0 apps.skype.com 
# 0.0.0.0 s.gateway.messenger.live.com

**Comment by ItsCEED** [comment]
Does not work..

**Comment by PavelSolovev** [comment]
I made so
```
#0.0.0.0 m.hotmail.com
#0.0.0.0 s.gateway.messenger.live.com 
```
After edit hosts: flushdns and remove skype folder from appdata

Skype works. Without ads.

**Comment by psimona** [comment]
Just tested works for me too. The no ads thing is really nice ^^

**Comment by psimona** [comment]
Does anybody know where the hosts file is saved in this application? (source code)

**Comment by leak** [comment]
I can confirm this issue.
The solution proposed by @PavelSolovev  works for me.
@psimona https://github.com/Nummer/Destroy-Windows-10-Spying/blob/master/DWS/MainDwsForm.cs#L777

**Comment by DJSlider** [comment]
HERE THE SOLUTION:
Edit HOSTS file, add these lines or comments it:

# 0.0.0.0 api.microsofttranslator.com
# 0.0.0.0 apps.skypeassets.com
# 0.0.0.0 dev.microsofttranslator.com
# 0.0.0.0 download.skype.com
# 0.0.0.0 login.live.com #Skype Login
# 0.0.0.0 secure.skypeassets.com
# 0.0.0.0 static.skypeassets.com
# 0.0.0.0 s.gateway.messenger.live.com #Status, Contact list!

**Comment by psimona** [comment]
Pull request to fix this above

**Comment by chaosua** [comment]
#0.0.0.0	s.gateway.messenger.live.com 
commenting only this line unlocked my skype connection

**Comment by skyr1s** [comment]
For Skype: 8.16.0.4 comment in hosts:
# 0.0.0.0 login.live.com
It Works for me

**Comment by fuerzaaa** [comment]
unlock in brandmayer and host-64.4.23.0-64.4.23.255 and Skype will work

**Comment by SuperRarePepe** [comment]
nothing of the described above works for me. I just used latest version of destroy windows 10 spying, trying to comment out lines suggested in hosts file, the only line present is `# 0.0.0.0 client-s.gateway.messenger.live.com`

Flushing dns and deleting skype folder in appdata doesn't help.

Could someone elaborate how do I "unlock firewall" and "host: 64.4.23.0-64.4.23.25" like suggested by user above? thanks

**Comment by Volgare** [comment]
Hi 
For solve this problem i had just disable the rule "157.55.235.0-157.55.235.255_Block" in the firewall windows defender in outbound traffic rules. Reload skype and problem solved. Tanks for your help

**Comment by JoeFromYT** [comment]
@SuperRarePepe Ty SOOOO MUCH FOR THIS!

**Comment by Rolf-Smit** [comment]
@SuperRarePepe This is the only solution working for me so far, I did however not remove the rules, I just disabled them. Only disabling "157.55.235.0-157.55.235.255_Block" as suggested by @Volgare is not working for me.

**Comment by Jedihoth** [comment]
@DJSlider **I dont have these lines in hosts file at all!**
api.microsofttranslator.com
apps.skypeassets.com
dev.microsofttranslator.com
download.skype.com
login.live.com #Skype Login
m.hotmail.com #Skype Connect
secure.skypeassets.com
static.skypeassets.com

this doesnt fix a problem, why we should argue ? where is ultimate solution from the developer??

**Comment by Jedihoth** [comment]
Only SKYPE that works fine after DWS activation is Skype from Windows Store, if you are happy with this version, fine! I use Classic version of Skype and I cant find a solution how I can get it back to work.

**Comment by Jedihoth** [comment]
THIS FIXED THE ISSUE FOR ME 
**"unlock the firewall and host: 64.4.23.0-64.4.23.255 and Skype will work"**

**Comment by kazoooka** [comment]
Nothing of all of this helped for me.... 
Got Skype Desktop version 8.25.0.5... I tried all of the steps....

**Comment by SuperRarePepe** [comment]
kazooka, having same issues after updating to 8.25.0.5

**Comment by opsach** [comment]
Just updated skype to 8.25.0.5 and having a same problem, but found a solution

I used notepad ++ to open hosts file than I was searching for any link in list that contain live and skype.
Than I deleted them all restarted skype and everything is working now

**Comment by john5286** [comment]
Hi. I am a total noob. If anyone could help it would be much appreciated! I ran DWS but am not sure how to add hosts etc. My has stopped working after i ran DWS...

**Comment by burn1ng** [comment]
> nothing of the described above works for me. I just used latest version of destroy windows 10 spying, trying to comment out lines suggested in hosts file, the only line present is `# 0.0.0.0 client-s.gateway.messenger.live.com`
> 
> Flushing dns and deleting skype folder in appdata doesn't help.
> 
> Could someone elaborate how do I "unlock firewall" and "host: 64.4.23.0-64.4.23.25" like suggested by user above? thanks
> 
> Update: Tried deleting all entries in hosts, to check if it's something blocking in this file, but no, skype still does not connect.
> 
> Update: tried to allow skype in firewall, it is allowed there anyway, tried to enabling/disabling, no use.
> 
> Update: running these commands helped:
> 
> `netsh advfirewall firewall delete rule name="157.55.235.0-157.55.235.255_Block"`
> `netsh advfirewall firewall delete rule name="157.55.56.0-157.55.56.255_Block"`
> `netsh advfirewall firewall delete rule name="64.4.23.0-64.4.23.255_Block"`
> `netsh advfirewall firewall delete rule name="65.55.223.0-65.55.223.255_Block"`

0. uninstall all previous skype vesrions with revo uninstaller (with cleaning all skype junk)
1. open cmd.exe as administrator and run theese 4 commands from comment above
2. also `ipconfig /flushdns` in cmd.exe with administrator rights
3. download and install skype from https://www.skype.com/ru/get-skype/
3. ????
4. PROFIT!!!

**Comment by jqlm** [comment]
> > nothing of the described above works for me. I just used latest version of destroy windows 10 spying, trying to comment out lines suggested in hosts file, the only line present is `# 0.0.0.0 client-s.gateway.messenger.live.com`
> > Flushing dns and deleting skype folder in appdata doesn't help.
> > Could someone elaborate how do I "unlock firewall" and "host: 64.4.23.0-64.4.23.25" like suggested by user above? thanks
> > Update: Tried deleting all entries in hosts, to check if it's something blocking in this file, but no, skype still does not connect.
> > Update: tried to allow skype in firewall, it is allowed there anyway, tried to enabling/disabling, no use.
> > Update: running these commands helped:
> > `netsh advfirewall firewall delete rule name="157.55.235.0-157.55.235.255_Block"`
> > `netsh advfirewall firewall delete rule name="157.55.56.0-157.55.56.255_Block"`
> > `netsh advfirewall firewall delete rule name="64.4.23.0-64.4.23.255_Block"`
> > `netsh advfirewall firewall delete rule name="65.55.223.0-65.55.223.255_Block"`
> 
> 1. uninstall all previous skype versions with revo uninstaller (with cleaning all skype junk)
> 2. open cmd.exe as administrator and run theese 4 commands from comment above
> 3. comment next lines in hosts:
>    #0.0.0.0 m.hotmail.com
>    #0.0.0.0 client-s.gateway.messenger.live.com
> 4. also `ipconfig /flushdns` in cmd.exe with administrator rights
> 5. download and install skype from https://www.skype.com/ru/get-skype/
> 6. PROFIT!!!
> 
> p.s. some problems can be if your Windows Defender is enabled. If nothing helps, try to disable it, both for private and public networks, and add Skype to acceptable applications for Windows Defender.

Big thanks, it's works
