### ISSUE TITLE
Undo any changes made by DWS

### ISSUE THREAD

**Issue by k3lt** [Nummer/Destroy-Windows-10-Spying#277]
Can we have this option please in case we screw something up?

**Comment by amaklp** [comment]
Yeah, like enable Windows Defender again?

**Comment by ioannisemmanou** [comment]
I really want to use the modern Windows 10 photo viewer because it is a decent viewer program. Unfortunately there is no way to undo this action (I read the warnings beforehand)

+1 for undo function

**Comment by tballas** [comment]
@amaklp I was able to turn windows defender back on by editing the registry with regedit and going to this key: http://gpsearch.azurewebsites.net/#2630 and setting the value to 0

Hope that helps you and others.
