### ISSUE TITLE
Windows Hello no longer working

### ISSUE THREAD

**Issue by oliesjeik** [Nummer/Destroy-Windows-10-Spying#283]
Although I do like the idea of removing all spying software from Microsoft and third party's there is one feature which I did like and that was Windows Hello.

On my surface pro 4, I was able to log in by facial recognition but unfortunately this is no longer working. I suspect this also counts for fingerprint recognition although my surface doesn't have one. When going into the 'setup for face sign-in'  it tells me that some settings are being managed by my organization...

Is it possible to put this feature back on and what would I be giving up by doing that?

Thanks for the reply,

Thomas

**Comment by xaricx** [comment]
I've had luck with starting the Windows Biometrics Service and setting it to autostart. Although, anytime you run AWS_Lite, it will be disabled.

**Comment by contesauce** [comment]
Unfortunately I'm having the same issue, and the Windows Biometric Service didn't fix it for me.

**Comment by Xanarkan** [comment]
Hello, 

I have the same problem.
I've tried to start the Windows Biometrics Service but this didn't solve.
I've also tried to uninstall / reinstall the fingerprint drivers on my laptop.

For information it's a Lenovo X1 Carbon 4th Generation with Windows 10 Professional installed and just before DWS it was perfectly functionnal.

Any plan to correct this bug or any solution to revert this without reinstalling the entire operating system ?

**Comment by contesauce** [comment]
Xanarkan, I did have some luck with re-enabling the camera through group policy and regedit, but it was never like stock. Unfortunately I tried to do a wipe with retaining files and this didn't fix it for me. I had to do a complete wipe, twice. Then everything started working again. Now I made sure to make a backup of all my system.

**Comment by contesauce** [comment]
All we really need is for the developer to tell us what triggers were changed in regedit to reverse them ourselves.

**Comment by Xanarkan** [comment]
After a search I was able to re enable the biometric service through the Local Group Strategy Editor.
For me it work like before.

**Windows+R -> gpedit.msc and then: Computer components -> Administration module -> Windows components -> Biometric (sorry if the traduction isn't right, I have it in French).
Enable all in this section et reboot the computer, you will have all biometric function back to normal.**

You can restore all the function you want trough the Local Group Strategy Editor and other trick if you want, for me I've just reactivate the Biometry cause I like to unlock my computer with the fingerprint.

Also, the code is open, so in fact you can analyse what the program do to your computer, not easy to read the code, but possible. The best is if the dev put some info in the read me or directly in the program.

Anyway, I'm glad this program kill almost all the spying features on my laptop, I don't like to be watched.

**Comment by SovietSam** [comment]
Xanarkan, works like a charm! Thanks!

**Comment by nanusl** [comment]
https://www.tenforums.com/tutorials/117987-enable-disable-windows-hello-biometrics-windows-10-a.html
