### ISSUE TITLE
State of the project? Many forks, many translations not merged

### ISSUE THREAD

**Issue by timofonic** [Nummer/Destroy-Windows-10-Spying#286]
Hello.

Could anyone say the status of this project? I see there are many forks of it, including ones with complete translations.

Kind regards.

**Comment by DarkKnight64** [comment]
dead?

**Comment by Wohlstand** [comment]
alive, but developing very slow, just support, fixing, extending with destroying a newly researched spy methods, etc.

**Comment by indig0F10w** [comment]
Nope, this software is dead. Use PowerShell scripts instead.

**Comment by mailinglists35** [comment]
@indig0F10w what scripts? can you post url?

**Comment by indig0F10w** [comment]
Sure, [https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/remove-default-apps.ps1].
