### ISSUE TITLE
GPOs and WSUS not working

### ISSUE THREAD

**Issue by ruboncio** [Nummer/Destroy-Windows-10-Spying#287]
Hello,

We installed this app in a master image to be deployed to 300 laptops.
Unfortunately it seems to block any Windows update even if they are pushed from WSUS.
On the plus side, some GPOs seem not to be working. Example - Power plans or close lid etc..

Is there a way to revert this? Is there a list with all the registry keys touching this?

Thanks

**Comment by Wohlstand** [comment]
Seems if Windows update is disabled, means disabled completely. Windows 10's update system is not same as on previous versions and even works like bit-torrent without WSUS, just pulling stuff from nearest neighbours. You may try to enable update back (that allowed by tool)

**Comment by ruboncio** [comment]
Hi Wohlstand,

Thanks for your advice, but unfortunately GPOs from the domain controller don't work.
It seems like there is some registry key or local policy that blocks anything pushed.
Local Policy works in a parent level so I have absolutely no way of pushing anything from the domain.

I need a list of all registry changes so I can figure it out what is blocking the deployment.

Regards

**Comment by Wohlstand** [comment]
GPO is works very weird even on older Windows machines. Usually it must work when you logged in with domain user and using machine local accounts usually ignoring domain's policy.

**Trivia:** I remembering how I annoyed to configure one tiny parameter to let it work on all workstations. I had my own domain network at home and everyone worked on machine under domain. Just wanted to use movable account for myself to work at bedroom at day and on kitchen at night. But I totally annoyed with AD (fun fact: "Ад" word in Russian is a "hell") and worst stability of Windows Server itself, moved to Linux and let machines use their local accounts. Linux based SAMBA Server doesn't requires have same login/password and same workgroup to use shares, that also annoying on Windows to have duplicated user accounts to just share folders.

**Comment by ruboncio** [comment]
We have Windows 2012 R2 and yes it does support Win10.
The thing is if I install a laptop from scratch, domain it and put into a OU, any GPO works flawless.
So it is clearly something that DWS blocks.

And of course, there is no way of re-imaging 300 laptops! It could take months.
Easiest way is to know what registry keys DWS changes and then roll them back to default by using a .bat that can be pushed with our KBOX. (That's my idea)

**Comment by Wohlstand** [comment]
Which check in the advanced params you think kills GPOs?
Anyway, everything that done by DWS, written here:
https://github.com/Nummer/Destroy-Windows-10-Spying/blob/master/DWS/MainDwsForm.cs
