### ISSUE TITLE
Проблема со Скайпом

### ISSUE THREAD

**Issue by gShurik** [Nummer/Destroy-Windows-10-Spying#289]
После запуска на Windows 7 x64 скайп перестал отправлять и принимать текстовые сообщения, на видеозвонках не отразилось. Проблема пропала только после восстановления файла hosts.

**Comment by Wohlstand** [comment]
Метрошный или классический? Видимо в hosts по ошибке был заблокирован скайповский сервер. Хотя, Мелкомягкие могли его использовать для передачи данных для шпионажа, не по назначению.

**Comment by gShurik** [comment]
Классический... Находил в хостах 0.0.0.0 ui.skype.com пробовал комментировать, но результата не дало, похоже все подряд сервера перебирать придётся.

**Comment by Wohlstand** [comment]
Попробуй закомментировать m.hotmail.com и s.gateway.messenger.live.com"

**Comment by gShurik** [comment]
Да, теперь работает. Попробую пару раз перезагрузиться чтобы наверняка проверить.

**Comment by gShurik** [comment]
Порядок, нужно какое-нибудь примечание к утилите сделать, чтобы в случае проблем разблокировали эти сервера. :)

**Comment by Wohlstand** [comment]
Да уже есть предложенный фикс, чтобы это не портить, если его примут, то следующая версия утилиты не будет это портить
