### ISSUE TITLE
Internet Explorer 11 / Edge Developer Tools Network tab broken

### ISSUE THREAD

**Issue by leak** [Nummer/Destroy-Windows-10-Spying#295]
Using this tool breaks the network tab in IEs Developer Tools by disabling the "Microsoft (R) Diagnostics Hub Standard Collector Service" service.
Re-enabling the service fixes the issue.

Win 10 x64 1607

**Comment by Bryantdl7** [comment]
From my small knowledge of windows services, it sounds like IE + edge need to have that service to function, but that is the catch since that service reports to MS
