### ISSUE TITLE
I use Skype for learning English.

### ISSUE THREAD

**Issue by vadim701** [Nummer/Destroy-Windows-10-Spying#296]
Skype is very important for me . I use Skype for learning English. Please answer what I need to do to make Skype work . And your program is the only one that allowed me to install Solidworks for the study. Thank you.

**Comment by Grety** [comment]
@vadim701, You provide too little info to indicate a problem. What are the versions of software youre using, how does the problem occur? Error messages, logs, behavior?

**Comment by Dreyk007** [comment]
Try to remove these lines from hosts file:

m.hotmail.com
s.gateway.messenger.live.com

**Comment by fortael** [comment]
That's true, skype don't working. Which option should i disable in program?

**Comment by Wohlstand** [comment]
Yea, It's duplicate of #289 , #278
