### ISSUE TITLE
Tool changes Adobe Acrobat DC icon in Start Menu

### ISSUE THREAD

**Issue by Paramood** [Nummer/Destroy-Windows-10-Spying#297]
The icon of Adobe Acrobat DC shortcut became like an icon of TIFF format. It happened after I used function 'Set default windows photo viewer'. And also this function makes icons of all of pictures like TIFF icon but imageres.dll has icons for JPG, PNG, GIF and others popular formats. It will be fine if tool changes pictures icons to them native icons (like on Windows 7 and 8.1). And also ICO format has icon like TIFF but it must have it's own icon (like on Windows 7, 8.1).

System: Win 10 Enterprise with last updates on this moment.
Tool version: 1.6 Build 722

![acrobat](https://cloud.githubusercontent.com/assets/26360776/23832059/5a3534de-0736-11e7-9d01-4b7375d4de2b.png)
![acrobat shortcut](https://cloud.githubusercontent.com/assets/26360776/23832060/5a35a8d8-0736-11e7-8f33-2ce670383ce2.png)

**Comment by Atavic** [comment]
You can reselect the .ico on the file properties tab.

**Comment by Paramood** [comment]
How?

**Comment by Atavic** [comment]
Sorry I didn't see some entries are greyed out, but there's a simple solution:
Find the location of the executable then right-click and Create Shortcut.
Now replace the broken shortcut in the metro GUI with the shortcut previously created.

**Comment by Paramood** [comment]
I understand that I can replace the shortcut. But the same icon is on Task Panel. It changed somewhere in OS and reinstalling Acrobat doesn't help. I would like to know how to fix it. I think that in Registry. But I don't know where exactly.

**Comment by Atavic** [comment]
It appears that the entries to the executable were deleted from the icon properties.

**Comment by Paramood** [comment]
Don't you know how to fix it?

**Comment by Atavic** [comment]
I can't give you precise instructions, but when you find the locations of the executable and the link appearing broken, you just have to replace it.
