### ISSUE TITLE
Firewall rule "MS telemetry block 1" also blocks public MSFT sites (connect.microsoft.com)

### ISSUE THREAD

**Issue by afiresnake** [Nummer/Destroy-Windows-10-Spying#3]
Tiny issue: One of the firewall rules ("MS telemetry block 1", 65.48.0.0/13) also blocks access to at least https://connect.microsoft.com (resolves to 65.55.58.14 for me).

But great stuff!

**Comment by Nummer** [comment]
Ok. 
TODO: Fix

**Comment by Nummer** [comment]
Fixed

**Comment by Acimaz** [comment]
how can i undo this telenetry block on my pc?
Have exactly this problem since i installed Destroy-Windows-10-Spying..
