### ISSUE TITLE
Skype

### ISSUE THREAD

**Issue by Rhastae** [Nummer/Destroy-Windows-10-Spying#301]
Unfortunately, even trying to delete:

#0.0.0.0 m.hotmail.com
#0.0.0.0 s.gateway.messenger.live.com 

For some reason, Skype continues to refuse to connect, and I'm clueless as to why. Any thoughts on how to proceed? What information would be required to give you a better insight into my problem? I'm a little out of my depth here.

Thanks in advance.

**Comment by Atavic** [comment]
You can use sysinternals TCPView on windows to see the connections made by an application.

**Comment by Rhastae** [comment]
Using that program, found the connections and addresses and double checked it's not blocked by host file or firewall.

No improvement :/
