### ISSUE TITLE
Windows 10 Creators Update

### ISSUE THREAD

**Issue by gongoscho** [Nummer/Destroy-Windows-10-Spying#302]
Is Windows 10 in Version 1703 (Creators Update) compatible?

grEEtZ

**Comment by ErfanDL** [comment]
No not compatible

**Comment by SidorovX86** [comment]
Anyone working on it?

**Comment by Bryantdl7** [comment]
Yes, any plans for updating this to the creators update?

**Comment by Zeroeh** [comment]
Latest release worked fine for me on creators update.

**Comment by ariefpizzuti** [comment]
The dev behind DWS said hes working on a new version .no ETA . translate from russian .
"Old version of DWS (Destroy Windows Spying) fails with espionage in new versions of Windows, 10.
In the development of the new version."
link from his twitter https://twitter.com/nummerok/status/831752017932644352
this is from Feb 2017 .if the current version works fine then ignore this .hope this helps
