### ISSUE TITLE
Windows search not working

### ISSUE THREAD

**Issue by Megarockdj** [Nummer/Destroy-Windows-10-Spying#311]

**Comment by Atavic** [comment]
Yes, because the search terms are sent home @ M$

**Comment by Mr-VIT** [comment]
@Megarockdj 
Enable Windows search --
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Search - AllowCortana=1

**Comment by Nummer** [comment]
This is Windows 10 problem. Wait to Win 10 DWS Edition =)
