### ISSUE TITLE
File History (maintenance mode) task is being disabled by this tool

### ISSUE THREAD

**Issue by agret** [Nummer/Destroy-Windows-10-Spying#312]
In the log it says:

[INFO] Disabled task: Microsoft\Windows\FileHistory\File History (maintenance mode)

I confirmed that this task was disabled. This task is not related to spying and is part of built-in Windows 10 Backup features that lets you keep a running backup of your documents folder and other folders that you pick to include in file history. You back them up to a network share or USB HDD then if something gets accidentally deleted/overwritten or the file becomes corrupt you just right click the folder and go to properties then select "File History" TAB and you can restore files back to older points in time.

It is not necessary to disable this service and doing so prevents the feature from working correctly.

**Comment by LeBaux** [comment]
Any progress on this?

**Comment by agret** [comment]
The app has not been updated since September 2016. Safe to say it has been abandoned by the developer and should not be used anymore. Try find an alternative that is safer.

**Comment by Nummer** [comment]
u can enable this task ?

**Comment by agret** [comment]
No worries, I have done by best to locate the offending issue for you.

I think it is in this file:
master/DWS/DWSResources.cs

Line 35 must be deleted
`@"Microsoft\Windows\FileHistory\File History (maintenance mode)",`
is how it currently reads. Removing this line from the file should resolve the issue.
