### ISSUE TITLE
Some firewall's rules block C++ redistribuable 2015 package installation

### ISSUE THREAD

**Issue by ptondereau** [Nummer/Destroy-Windows-10-Spying#313]
I didn't find the rule that cause it but by disabling all rules I can install such file: https://www.microsoft.com/fr-fr/download/details.aspx?id=48145

Because of network ressources, this installer can't download additionals files.

**Comment by kevit-development** [comment]
It installed for me, are you sure it's caused by DWS?

**Comment by oreyg** [comment]
Maybe you have ip of some regional server blocked?
Please check which ip its trying to access using [wireshark](https://www.wireshark.org/) or some other network analyzer.

**Comment by oreyg** [comment]
Ok, seems like one of the rules in host breaks BITS service.

**Comment by Nummer** [comment]
Hi. I block all M$ spyware ip adresses.
