### ISSUE TITLE
sometimes login windows,it takes about 10min.

### ISSUE THREAD

**Issue by sys234** [Nummer/Destroy-Windows-10-Spying#318]
I use the *Destroy-Windows-10-Spying* tool ,sometimes login windows,it takes about 10min,
my windows account is local administrator account,non online account,is there anyone occured the situation?

**Comment by Nummer** [comment]
please send windows boot log

**Comment by kevzdev** [comment]
I don't think this has to do with this simple anti spyware tool.

**Comment by Jedihoth** [comment]
cant login witn MS accout in MS Store, it says doent look like correct e-mail or somthing like that
