### ISSUE TITLE
is this program is discontinued or what?

### ISSUE THREAD

**Issue by theluckyman** [Nummer/Destroy-Windows-10-Spying#319]
I was wondering is software still active as auto-updater since I use it weekly to update or is it one time or what?  just wondering

**Comment by littleboot** [comment]
I'm would like to know this to, I love this program, and today I was looking to use it again for the latest windows 10 update, 3D builder and peoples bullshit adware just comes back, I can't even disable windows update.

**Comment by H3rmit** [comment]
I need to know this to

**Comment by Dmitrij-Polyanin** [comment]
Me too. I think it is the best tool and very want to continue it.

**Comment by comodoro** [comment]
Interested as well. There is the develop branch, but still six months old

**Comment by kevzdev** [comment]
It's updated.

@Nummer close this issue.
