### ISSUE TITLE
Unable to donate, program is win

### ISSUE THREAD

**Issue by squidgemidget** [Nummer/Destroy-Windows-10-Spying#321]
so like maybe we pay this dude and he makes moar

**Comment by littleboot** [comment]
I agree I'm willing to donate some money for his time and effort.

**Comment by squidgemidget** [comment]
jesus fucking christ the updater is back again >: c

**Comment by MrGKanev** [comment]
I think that everybody will give 1-2$ spare just for an update but we will see.
