### ISSUE TITLE
The program stops running

### ISSUE THREAD

**Issue by alexalsp** [Nummer/Destroy-Windows-10-Spying#323]
[INFO] Starting: 11.02.2018 20:40:53.
[INFO] 
Windows Version: Windows 10 Enterprise 2016 LTSB
Build: 14393.2035.amd64fre.rs1_release_inmarket.180110-1910

[INFO] Creating restore point DestroyWindowsSpying 11.02.2018 20:40:54...
[INFO] Restore point DestroyWindowsSpying 11.02.2018 20:40:54 created.
[INFO] Disable telemetry...
[INFO] Delete keylogger...
[INFO] Cortana disable #1
[INFO] Disable DcpSvc service
[INFO] Disable diagnosticshub.standardcollector.service service
[INFO] Disable DiagTrack service
[INFO] Disable SensrSvc service
[INFO] Disable dmwappushservice service
[INFO] Disable lfsvc service
[INFO] Disable MapsBroker service
[INFO] Disable NetTcpPortSharing service
[INFO] Disable RemoteAccess service
[INFO] Disable RemoteRegistry service
[INFO] Disable SharedAccess service
[INFO] Disable TrkWks service
[INFO] Disable WbioSrvc service
[INFO] Disable WMPNetworkSvc service
[INFO] Disable WSearch service
[INFO] Disable XblAuthManager service
[INFO] Disable XblGameSave service
[INFO] Disable XboxNetApiSvc service
[INFO] Disable HomeGroupListener service
[INFO] Disable HomeGroupProvider service
[INFO] Disable bthserv service
[INFO] Disable wscsvc service
[INFO] Disable WlanSvc service
[INFO] Disable OneSyncSvc service
[INFO] Disable AeLookupSvc service
[INFO] Disable PcaSvc service

and The program stops running. I waited for half an hour, but nothing has changed.

**Comment by Nummer** [comment]
FIxed in new version
