### ISSUE TITLE
Excess in blocked hosts

### ISSUE THREAD

**Issue by chybeat** [Nummer/Destroy-Windows-10-Spying#330]
Since ver v1.6.722 to 1.7.1 new urls/subdomains/ips are blocked via hosts file, but some blocked items are not necesary, like "login.live.com" (i can't read hotmail, for example), and in other hand not internet connection detected. My suggestion is, separate the hosts file block for apps. I want to block some spy but, not the acces to hotmail, skype or answers.microsoft.com,

**Comment by github-serenity3** [comment]
Absolutely agree with chybeat on the blocked hosts excessiveness.
login.live.com - Microsoft account is needed widely for a range of programs to extend licences, etc.
answers.microsoft.com - see a comment above.
login.live.com && s.gateway.messenger.live.com - my skype stopped working with them blocked.
And so on...
Maybe, DWS needs to get more flexible interface with the hosts divided into some groups, or so?

**Comment by kylethedude5** [comment]
> my skype stopped working with them blocked.

You do realize skype = spying right?

**Comment by chybeat** [comment]
Kylethedude5 i know, but I use Skype = your phone say's to apple/google where are/was (and probably) will you go... This thread is for an issue, discution and probably a solution, not for says the OBVIOUS things!
