### ISSUE TITLE
login.live.com blacklisted in hosts file

### ISSUE THREAD

**Issue by Stengell** [Nummer/Destroy-Windows-10-Spying#332]
i understand that we don't like microsoft spying, but blacklisting this in the hosts file seems a bit extreme, this prevents basically any service or webpage that use Microsoft login from working.

So i would encourage you to remove this from the block list :-)
or at least make it an option so it is visible that it is blocked.

**Comment by konstantin59** [comment]
yes. skype not working
[](http://www.imghost.in/image/PUM1Q)

**Comment by WestDragon** [comment]
I likewise have a problem

**Comment by Rishats** [comment]
Need fix skype!

**Comment by gegemon2012** [comment]
Yes. I also do not work skype web .

**Comment by Mayurifag** [comment]
same here with onenote 2016 app. what should we do to restore connection?

**Comment by webmaster4w** [comment]
Вход в Skype блокирован, пишет: Проблема при входе в Skype. Возможно, доступ блокируется плагином или программой блокировки рекламы InternetExplorer. Проверьте настройки InternetExplorer и повторите попытку позже.
Проверил здесь:
http://www.skaip.su/proverit-dostup-k-skaypu
Результат:
http://www.skaip.su/proverit-dostup-k-skaypu?6B49-2F2E-61EA-5A7E-FF4E
Помогите, кто решил вопрос. Не хочется Windows переустанавливать...

**Comment by konstantin59** [comment]
удалите строку login.live.com из файла hosts, и обновите скайп до версии 8

**Comment by Stengell** [comment]
btw if people are having problems just go into DWS and select edit HOSTS file and remove the line that contains login.live.com and hit save.

Just think it is creating a lot of problems for people who don't know what to do

**Comment by kylethedude5** [comment]
If people do not understand what the HOSTS file is they should not be editing it in the first place!
