### ISSUE TITLE
Skype NOT work after installing DWS 1.7.1

### ISSUE THREAD

**Issue by altium01** [Nummer/Destroy-Windows-10-Spying#334]
Skype STOP working after installing DWS 1.7.1
How I can bring Skype back to work and why in the interface there is missing option for exclude Skype from blocking????
Lets discuss how I can bring back Skype back to work, because its important!

**Comment by madmaximka** [comment]
btw if people are having problems just go into DWS and select edit HOSTS file and remove the line that contains login.live.com and hit save.
