### ISSUE TITLE
No Internet access

### ISSUE THREAD

**Issue by 3soolo3** [Nummer/Destroy-Windows-10-Spying#336]
2.2.2.2
But Internet works well
![no-internet-icon](https://user-images.githubusercontent.com/16206472/38197753-888204f2-3692-11e8-8740-ecf9d801c54f.gif)

**Comment by anfo55** [comment]
Same
![capture](https://user-images.githubusercontent.com/19360769/38453737-12a4ec50-3a8d-11e8-814a-7cb92a78372f.PNG)
