### ISSUE TITLE
Microsoft Store not work

### ISSUE THREAD

**Issue by 3soolo3** [Nummer/Destroy-Windows-10-Spying#337]
2.2.2.2
![ms-store](https://user-images.githubusercontent.com/16206472/38197956-59315396-3693-11e8-89ab-5f8c6478f3bc.png)

**Comment by Lassnochas** [comment]
not working microsoft store/ install prorgram and update error 0x80070422. Delete all rules defender and cleaning host all string, Enable Windows install servises. Nothing not change? problem stil.

**Comment by polochinoc** [comment]
Go to your C:\Windows\System32\drivers\etc directory, then edit your hosts file as an admin and comment all the lines that have the keyword "store" in them.

**Comment by Lassnochas** [comment]
![12](https://user-images.githubusercontent.com/12582725/38360604-522e6826-38d3-11e8-963b-82ecfdca3ab2.png)
![5](https://user-images.githubusercontent.com/12582725/38360605-52496f0e-38d3-11e8-8773-1194f309ddf6.png)
![6](https://user-images.githubusercontent.com/12582725/38360606-52654094-38d3-11e8-9c3b-3a13d95e8b1d.png)
![7](https://user-images.githubusercontent.com/12582725/38360607-52813308-38d3-11e8-9608-f8b12e90dde4.png)
![8](https://user-images.githubusercontent.com/12582725/38360608-529aeb72-38d3-11e8-86df-c326a4c7d932.png)
![9](https://user-images.githubusercontent.com/12582725/38360610-52b526ea-38d3-11e8-9cf2-305baab5e0c7.png)
![10](https://user-images.githubusercontent.com/12582725/38360611-52d0e79a-38d3-11e8-979a-0999ae7a0f65.png)
![11](https://user-images.githubusercontent.com/12582725/38360612-52eb83b6-38d3-11e8-80fc-1d240f14ded3.png)

**Comment by 3soolo3** [comment]
polochinoc
"Go to your C:\Windows\System32\drivers\etc directory, then edit your hosts file as an admin and comment all the lines that have the keyword "store" in them."
It work

**Comment by Lassnochas** [comment]
This was done and cleaned the firewall rules, shown in the screenshots above. But at the same time there are new errors, which are also shown in the screenshots.

**Comment by DrPhilPerlmutter** [comment]
@Lassnochas  
DWS writes certain entries that point some domains at nowhere into hosts, also it creates firewall rules that block outgoing connections to certain ip s.
5 of these entries to the hosts and 1 created firewall rule will cause the microsoft store not working, which are:

hosts:

0.0.0.0 pti.store.microsoft.com 	 				
0.0.0.0 store-images.s-microsoft.com 	 			
0.0.0.0 storeedgefd.dsx.mp.microsoft.com 			
0.0.0.0 storecatalogrevocation.storequality.microsoft.com	
0.0.0.0 licensing.mp.microsoft.com 	 

firewall:

Block of 191.232.139.2

Disabling these entries/rules made it working for me.

**Comment by Jedihoth** [comment]
@3soolo3 what do you mean by "comment all the lines"?? what i actually have to do? BTW my Skype doesnt work too, I cant log in..

**Comment by Jedihoth** [comment]
@DrPhilPerlmutter what all these 0.0.0.0 mean??? I am not a hacker.. Can someone explain in appropriate way??

**Comment by DrPhilPerlmutter** [comment]
@Jedihoth 
127.0.0.1 is a loopback ip address (localhost), 0.0.0.0 non-routable meta-address used to designate an invalid, unknown, or non-applicable target.

**Comment by Jedihoth** [comment]
@DrPhilPerlmutter Okaaay... shall I insert my IP address digits into HOST file instead of given 0-0-0-0 ??

**Comment by Jedihoth** [comment]
@DrPhilPerlmutter Looks like I got the hint. Thanks ! I do my best cuz English isn't my first language. Originally I am from Russia ;D

**Comment by Jedihoth** [comment]
@DrPhilPerlmutter wait! what about Skype??

**Comment by MlgResolve** [comment]
Thanks so much! This was driving me insane for such a long time and I knew it had something to do with the DWS rules but I didn't know what to change and what not to <3

**Comment by enriqxxx** [comment]
try disabling the following hosts in DWS --> Utilities --> "Open and edit HOSTS file".

Do Ctrl+F and search for "store". Disable individual URLs by adding # in front. Try to disable these:
0.0.0.0 pti.store.microsoft.com
0.0.0.0 store-images.s-microsoft.com
0.0.0.0 storeedgefd.dsx.mp.microsoft.com
0.0.0.0 storecatalogrevocation.storequality.microsoft.com

All of them should have "#" in front like this:

# 0.0.0.0 pti.store.microsoft.com
# 0.0.0.0 store-images.s-microsoft.com
# 0.0.0.0 storeedgefd.dsx.mp.microsoft.com
# 0.0.0.0 storecatalogrevocation.storequality.microsoft.com
Then, press file and save. Close the notepad. Try to re-open windows store.

ok
