### ISSUE TITLE
After installing DWS bluetooth doesn't work 

### ISSUE THREAD

**Issue by eryepa** [Nummer/Destroy-Windows-10-Spying#339]
My BT mouse doesn't work, and the system doesn't want to look for it. If I try to send a file, system says that BT file transfer is disabled by policy

**Comment by coleprime** [comment]
Same issue here.

**Comment by vbojilov** [comment]
Same here. Help on re-enabling my bluetooth please.

**Comment by vbojilov** [comment]
Did you guys check and try enabling the disabled "bthserv" service?

**Comment by vbojilov** [comment]
Solution for me and my problem as outline above was to go into my services, re-enable all of the blue-tooth based services (they start with "bluetooth..." in their name, and to also start them manually. I checked that my bluetooth was running, reset my computer, and so far so good. Hope this helps anyone else.

**Comment by chicco83** [comment]
same issue for me. dws kills my logitech mx master connection.
dws disables "bluetooth support service" and obviusly this is wrong.
please fix this

**Comment by Azzarok** [comment]
Just a little up, was it fix ? Cause I seem have the same problem, BT don't work. I saw different solutions tu fix it but always talk about Bluetooth support service in services.mcs, and I don't have it. The BT service is totally off. Anybody know how can I re-enable my Bluetooth pls ? Thank you !

**Comment by kiraaLeon** [comment]
Solution:
spanish : actualizar drivers con 3dp chip , seccion otros , icono mas , bluetooth.

**Comment by Azzarok** [comment]
> Solution:
> spanish : actualizar drivers con 3dp chip , seccion otros , icono mas , bluetooth.

Hi, sorry I don't really understand and so Google give such a bad translation, can you explain a little more please ? Thank you so much
