### ISSUE TITLE
Re-enable defender

### ISSUE THREAD

**Issue by LordMaxxie** [Nummer/Destroy-Windows-10-Spying#340]
Hi.
Is there a way to re-enable defender?

Thanks.

**Comment by KiUserExceptionDispatcher** [comment]
What for? The best way is not to install this toolkit.

**Comment by Notasinbeer** [comment]
Does that mean you don't know how to do it ? The question was, Is there a way to re-enable defender? If there is I would like to know also.

**Comment by agret** [comment]
Yes there is a way, I will try and submit a patch to this program to fix some things in it when I can work out how. Still new to github :)

**Comment by LordMaxxie** [comment]
Start a repository - https://github.com/new

**Comment by agret** [comment]
https://github.com/agret/windows-tweaks/archive/master.zip

REG file to enable defender is in there

**Comment by Nummer** [comment]
TODO: Add feature

**Comment by Notasinbeer** [comment]
@agret , Thank you !
