### ISSUE TITLE
Bluetooth doesn't work anymore. HELP

### ISSUE THREAD

**Issue by vbojilov** [Nummer/Destroy-Windows-10-Spying#341]
As stated. I need help on re-enabling my bluetooth please. I used DWS on my Home edition, and something pertinent to bluetooth connections are clearly disabled as my attempting to add a bluetooth device results in an automatic failure without even allowing a search. Please point me in the direction of what to look at re-enabling. I'm really looking forward to gaming with bluetooth on my semi-privacy-secured PC.

**Comment by vbojilov** [comment]
Solution for me and my problem as outline above was to go into my services, re-enable all of the blue-tooth based services (they start with "bluetooth..." in their name, and to also start them manually. I checked that my bluetooth was running, reset my computer, and so far so good. Hope this helps anyone else.

**Comment by kiraaLeon** [comment]
Solution:
spanish : actualizar drivers con 3dp chip , sección otros , icono mas , bluetooth.
