### ISSUE TITLE
Автор, уважаемый, памагити!!! Зачем всё это выключать и ломать?

### ISSUE THREAD

**Issue by Frashwater** [Nummer/Destroy-Windows-10-Spying#343]
Не работает почтовый клиент, магазин, иксбокс и домашняя группа!! (её то за что???)
Ещё раздражает уведомление о том что не удалось запустить защитник виндовс... Он у меня и так был отключён т.к. стоит каспер. Как убрать это уведомление? 
Магаз восстановил своими силами, иксбокс вроде тоже, у погоды не работает только живая плитка, никак не пойму какой адресс осталось разблочить? 
Службы домашней группы запущены, но ни один комп не может подключится к моему компу и не видит общедоступных папок, но в сети комп видят.
Помогите кто чем может...

**Comment by Notasinbeer** [comment]
Попробуйте открыть DWS, нажмите «Утилита», нажмите «Удалить старые правила брандмауэра DWS».
Затем перезагрузите компьютер. Посмотрите, работает ли это. Если у вас все еще есть проблемы, откройте DWS, нажмите «Утилита», затем «Восстановить систему». Выберите точку восстановления перед установкой DWS. Это должно заставить вас работать снова.
![dws utility 1](https://user-images.githubusercontent.com/36719872/38773465-f76f9f14-4001-11e8-848b-adc2f7eb3889.png)
![dws utility 2](https://user-images.githubusercontent.com/36719872/38773467-03899444-4002-11e8-95b6-d80d484b75c8.png)
![dws utility 3](https://user-images.githubusercontent.com/36719872/38773468-08fa90ea-4002-11e8-9363-1042b96b1b97.png)

**Comment by Frashwater** [comment]
Это вообще ничего не дало, а восстановление системы отключено. По этому я и прошу помочь вручную всё восстановить.

**Comment by madmaximka** [comment]
@Frashwater подними логи и включи сам всё назад. лог ведь есть.

**Comment by Notasinbeer** [comment]
You may have to back up your files, and try "Reset this PC". The "Read Me" does say most settings are permanent. I know it's not what you want to do, but there may be too many knots to undo to get it back to where you want ? In the end this might be the fastest way. And mind you I have not had the chance to try this myself, just thinking of a way to get you back to the beginning.
<img width="341" alt="read me" src="https://user-images.githubusercontent.com/36719872/38780672-31479dda-408f-11e8-8e4e-49586fd4a7b3.png">

**Comment by madmaximka** [comment]
@Notasinbeer he turn off system restore...

**Comment by sergeyouem** [comment]
Насчёт магазина я разобрался. Не надо блокировать Win 10 Metro, в которые и входит магазин.  А его адреса я так и не нашёл.

**Comment by KiUserExceptionDispatcher** [comment]
Зачем отключать слежение если вы используете магазины и дефендеры?

**Comment by Frashwater** [comment]
@KiUserExceptionDispatcher Я же написал что не использую защитник вин, у меня каспер, а что такого в магазине? В винде другие службы есть которые много инфы собирают и скрины делают, кейлогеры и прочее, вот их я и хочу заблокировать. Предыдущие версии dws вроде как это и делали, а вот последняя вообще превращает винду в тыкву.

**Comment by Frashwater** [comment]
@sergeyouem с магазином я сам разобрался давно) Погоду недавно оживил, но всё ещё не работает живая плитка(какой то адрес в хосте заблокирован) и не работает домашняя группа.

**Comment by Jedihoth** [comment]
странный тип, если нужна погода и общий доступ к папкам зачем устанавливать это ПО?

**Comment by Frashwater** [comment]
@Jedihoth Предыдущие версии не ломали эти функции, просто винда превращается в тыкву после этой проги. Общий доступ к папкам то зачем ломать?

**Comment by Jedihoth** [comment]
@Frashwater про тыкву верно подмечено, а смысл? винда и так вся дырявая а вы делаете общий доступ к файлам и хотите анонимности?? Это как стремиться похудеть не прекращая жрать

**Comment by Frashwater** [comment]
@Jedihoth Так ведь общий доступ в локальной сети в квартире и только к определённым файлам типа музыки и кино

**Comment by Aleksey1992UA** [comment]
> @sergeyouem с магазином я сам разобрался давно) Погоду недавно оживил, но всё ещё не работает живая плитка(какой то адрес в хосте заблокирован) и не работает домашняя группа.

так как магазин включить то????

**Comment by Frashwater** [comment]
@Aleksey1992UA  Никак, смею предположить что вы обновляли винду на версию 1803, а при этом магазин убивается на 100% У меня на всех обновившихся компах это произошло. Мне просто надоело мучиться  и я переустановил винду.

**Comment by madmaximka** [comment]
> @Aleksey1992UA Никак, смею предположить что вы обновляли винду на версию 1803, а при этом магазин убивается на 100% У меня на всех обновившихся компах это произошло. Мне просто надоело мучиться и я переустановил винду.
кстати, новый разработчик убрал вирусы из своего софта?
предыдущий разработчик сообщал о заразе внутри.

**Comment by Aleksey1992UA** [comment]
> @Aleksey1992UA Никак, смею предположить что вы обновляли винду на версию 1803, а при этом магазин убивается на 100% У меня на всех обновившихся компах это произошло. Мне просто надоело мучиться и я переустановил винду.
гениальное приложение. Просто бл генальное

**Comment by Aleksey1992UA** [comment]
@Frashwater 
самое ущербное в этом всем, что процессы приложений типа магазина и иксбокса все равно висят и жрут ресурсы
и дернул меня черт попробовать эту срань

**Comment by madmaximka** [comment]
> 
> 
> @Frashwater
> самое ущербное в этом всем, что процессы приложений типа магазина и иксбокса все равно висят и жрут ресурсы
> и дернул меня черт попробовать эту срань

автор другой. вот и срань вышла.

**Comment by daniknewgarden** [comment]
@sergeyouem Я правильно сделал?

**Comment by daniknewgarden** [comment]
https://support.microsoft.com/uk-ua/help/972034/how-to-reset-the-hosts-file-back-to-the-default нужно просто обнулить файл hosts по инструкции
