### ISSUE TITLE
Microsoft Store не получает доступ в сеть

### ISSUE THREAD

**Issue by sergeyouem** [Nummer/Destroy-Windows-10-Spying#344]
Какие правила и адреса фаервола и в файле host убрать для доступа в сеть?

**Comment by sergeyouem** [comment]
Отвечаю сам себе : не блокировать Win 10 Metro, в которые входит и Windows Store.

**Comment by sunyink** [comment]
尝试后发现光以上几项不够（似乎在我这里会无法完成授权，进而无法下载）。
使用二分法大概确定了一组host如下
`#0.0.0.0 dmd.metaservices.microsoft.com 
#0.0.0.0 dns.msftncsi.com 
#0.0.0.0 feedback.microsoft-hohm.com 
#0.0.0.0 feedback.search.microsoft.com 
#0.0.0.0 feedback.windows.com 
#0.0.0.0 img-s-msn-com.akamaized.net 
#0.0.0.0 insiderppe.cloudapp.net 
#0.0.0.0 licensing.mp.microsoft.com 
#0.0.0.0 mediaredirect.microsoft.com 
#0.0.0.0 msftncsi.com 
0.0.0.0 officeclient.microsoft.com 
##0.0.0.0 oneclient.sfx.ms 
#0.0.0.0 pti.store.microsoft.com `
另外，搜索host中带“store”的也自然要开放它。也希望有志之士能分析出具体是哪几个。终于能下新东西了.....
