### ISSUE TITLE
No me activa la detección de redes!!

### ISSUE THREAD

**Issue by Angelo2009** [Nummer/Destroy-Windows-10-Spying#346]
Buen día.. detecte el problema en varias PCs que use DWS de que no activa la detección de redes desde la configuración de uso compartido avanzado.. la activo, guardo los cambios y cuando reviso sigue desactivada.. 
Alguien conoce una solución?
Gracias!

**Comment by Angelo2009** [comment]
Me auto-respondo y también para ayudar a quien le pase lo mismo.

Revisa que este iniciados los servicios de Windows:
-Servidor
-Estación de trabajo
-Detección SSDP
-Aplicación auxiliar de NetBIOS sobre TCP/IP
-Dispositivo host de UPnP

Saludos!

**Comment by Nummer** [comment]
fixed on 1.0 release
