### ISSUE TITLE
Can't enable Windows Defender 

### ISSUE THREAD

**Issue by polochinoc** [Nummer/Destroy-Windows-10-Spying#347]
Hello everyone, I'm having trouble reenabling Windows Defender. Does anyone have an idea on what to modify to be able to activate it ? Thank you for your time.

**Comment by agret** [comment]
https://github.com/agret/windows-tweaks/archive/master.zip

REG file to enable defender is in there

**Comment by Nummer** [comment]
TODO: Add enable Windows Defender feature
