### ISSUE TITLE
Can't connect to Bing anymore

### ISSUE THREAD

**Issue by VahidN** [Nummer/Destroy-Windows-10-Spying#354]
```cmd
ping www.bing.com

Pinging a-0001.a-msedge.net [204.79.197.200] with 32 bytes of data:
General failure.
General failure.
General failure.
General failure.

Ping statistics for 204.79.197.200:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```

**Comment by itestings** [comment]
Check \hosts for this address and remove that from hosts or from firewall.

**Comment by VahidN** [comment]
Well, That's true. My intention was to report it for the next releases.
![blockbing](https://user-images.githubusercontent.com/766010/39693309-d698769a-51f8-11e8-824d-89b046303bab.png)
