### ISSUE TITLE
Skype Connection Issue

### ISSUE THREAD

**Issue by kapeeo** [Nummer/Destroy-Windows-10-Spying#357]
Hello guys,

I updated windows 10 to build 1803, clared file hosts and applied latest DWS and final build 1.7.1, downloaded latest Skype version 7.41.0.101, removed s.gateway.messenger.live.com line from hosts file, clear dns from command prompt and still can't manage to connect to skype.

Any help?

If you need more information just ask me

Thanks in advance

**Comment by Alkaris** [comment]
You deleted from your hosts file, but you didn't remove the firewall rules for it..

**Comment by kapeeo** [comment]
How to remove the firewall rules?

**Comment by Alkaris** [comment]
> How to remove the firewall rules?

Open Windows Firewall duh?

**Comment by kapeeo** [comment]
Tried a lot, but couldn't find how to restore it.

Any clues?

**Comment by chybeat** [comment]
Hi, to unlock Skype (tested with version 7.40.0.151) you need to delete the firewall rules called:

157.55.235.0-157.55.235.255_Block
157.55.56.0-157.55.56.255_Block
64.4.23.0-64.4.23.255_Block
65.55.223.0-65.55.223.255_Block

or use this commands:
netsh advfirewall firewall delete rule name="157.55.235.0-157.55.235.255_Block"
netsh advfirewall firewall delete rule name="157.55.56.0-157.55.56.255_Block"
netsh advfirewall firewall delete rule name="64.4.23.0-64.4.23.255_Block"
netsh advfirewall firewall delete rule name="65.55.223.0-65.55.223.255_Block"

I hope be useful.  :)

**Comment by SuperRarePepe** [comment]
chybeat you saved my life

**Comment by kapeeo** [comment]
chybeat you are a legend mamen!

Thanks so much, worked perfectly!
