### ISSUE TITLE
NOT FUNCTION PROPERLY

### ISSUE THREAD

**Issue by nurexy** [Nummer/Destroy-Windows-10-Spying#36]
how can i enable windows spy ware after enabling it?

**Comment by Nummer** [comment]
?

**Comment by malware1-2** [comment]
I think "after disabling it?" was supposed to be "after disabling it?". So basically he wants to undo the changes done by DWS.

**Comment by TRoskop** [comment]
Hello nurexy,
this software creates a system recovery point before applying changes.

So use Windows recovery!
