### ISSUE TITLE
*URGENT* DWS created weird startup items - virus?

### ISSUE THREAD

**Issue by deksar** [Nummer/Destroy-Windows-10-Spying#375]
Today, when I opened DWS (downloaded from official website renessans.bz), DWS fetched an executable file called "updater.exe", and this file ran automatically, then my Windows 10 resetted itself. Afterwards, the system started running weirdly - checked msconfig, and I saw a lot of items starting automatically, these were NOT there before I ran DWS. I am sure of that - I check it regularly. There are fake "Avast" items as well.

So, is DWS a virus now? It was, once upon a time, a cool tool. Dorogoi dlinnoyu.

Here are the items I've mentioned about: 
https://pasteboard.co/HpOU6e9.png

**Comment by hooddy** [comment]
I agree. Why does it reboot PC with no any messages? Why it do anything whith no any user actions n permission?

**Comment by deksar** [comment]
You didn't get it. I say, DWS installed virus on the system.

**Comment by hooddy** [comment]
I get all i need. Just use SmartFix to restore Windows or reisntall it. And report abuse at github.

**Comment by Nummer** [comment]
The reboot is carried out in connection with the fix bugs in the penultimate version, we apologize for the inconvenience, and as the DWS virus has always been recognized by antiviruses.
