### ISSUE TITLE
site not working!

### ISSUE THREAD

**Issue by epexa** [Nummer/Destroy-Windows-10-Spying#378]
site https://renessans.bz not working...

please upload binary files in github.

**Comment by epexa** [comment]
@Nummer

**Comment by epexa** [comment]
@malware1-2

**Comment by epexa** [comment]
@BlackRouter

**Comment by Lonely70mato** [comment]
Dev is a cuck

**Comment by epexa** [comment]
@Nummer @malware1-2 @BlackRouter please upload binary file http://download.renessans.bz/DWS.exe to this repository!

**Comment by natrius** [comment]
Still not working, would like to use it :)

**Comment by BlohoJo** [comment]
Looked very promising. Too bad.

**Comment by HorlogeSkynet** [comment]
Hi

As the releases over here do not contain any binaries, this repo is pretty useless for most of the project use cases...
Could you upload it / them here as long as on your website please ?

Thanks
Bye

**Comment by xkpx64** [comment]
Actually is not useless , you can always compile it with MVS2015... It's simple to do.
I did it myself last night and now i got my own binary and i can edit some stuff and maybe add some more and start posting some commits 🗡

**Comment by HorlogeSkynet** [comment]
Happy for you, but when you are on a "casual" computer MSV is not installed, and it would be very handy if an executable was available.

**Comment by epexa** [comment]
@Lonely70mato @natrius @BlohoJo @HorlogeSkynet @xkpx64 and others!

**LATEST VERSIONS HERE (INCLUDING BINARIES):
https://github.com/Wohlstand/Destroy-Windows-10-Spying/releases**
