### ISSUE TITLE
Remove Windows version checkin

### ISSUE THREAD

**Issue by hooddy** [Nummer/Destroy-Windows-10-Spying#38]
Можно ли убрать проверку версии винды (ну или хотя бы добавить висту в допустимые версии)? Хочу под Вистой запускать, хотя бы чтобы правила в файрволл и хостс добавить. Ну т.е. понятно, что за последствия использования на висте я сам отвечаю, без претензий.

**Comment by Nummer** [comment]
Сам убери, и скомпилируй.

**Comment by hooddy** [comment]
Я не разработчик. Можно было послать и помягче, хотя ничего другого и не ожидал от наших.

**Comment by Nummer** [comment]
Для висты эта программа не разрабатывалась, и не будет никогда доступна официально.

**Comment by hooddy** [comment]
Вот это уже больше похоже на ответ. Я попробовал запустить через верификатор - вывалилась. Пока, тем не менее, посижу на Висте, пока вы все, разработчики, не найдете все бекдуры в Семерке. В любом случае, за софт спасибо.

**Comment by Nummer** [comment]
Ставь Win 7 build 7601 , и не парься. Центр обновлений не включай никогда, и всё чики пуки будет)
