### ISSUE TITLE
Privacy settings; Microphone (crashes) 1803

### ISSUE THREAD

**Issue by Snky** [Nummer/Destroy-Windows-10-Spying#380]
Hello, after running the application my microphone no longer works. When I go to PC Settings then Privacy and then Microphone the window closes itself.

Does anyone know a workaround? A way to rollback a certain change?
Any services that need re-enabling?

**Comment by Snky** [comment]
Capability Access Manager Service

**Comment by mrdhruvjoshi** [comment]
Thanks a lot man! I was trying to solve this issue form a month. wasted my money on three mics and 1 camera but issue was not resolved. now issue is resolved. I turned off that service caused this issue.

**Comment by OlleNeiman** [comment]
Thanks for finding the required service! I was about to reformat (again). Microsoft support is useless for "advanced" issues.

**Comment by Emanx140** [comment]
Thank you!

**Comment by TriStarGod** [comment]
Been driving me nuts. Thanks!
