### ISSUE TITLE
How about adding ips and networks as null-routes instead of firewall roules?

### ISSUE THREAD

**Issue by eugenenv** [Nummer/Destroy-Windows-10-Spying#39]
as title says..

**Comment by Nummer** [comment]
I'll think about it.

**Comment by Nummer** [comment]
no.

**Comment by eugenenv** [comment]
but why? it's even more effective than windows firewall rules, not everybody keeps it enabled ant makes sure than any win-software won't bypass default firewall (we can not be sure)
