### ISSUE TITLE
program is no running from a network share.

### ISSUE THREAD

**Issue by Nummer** [Nummer/Destroy-Windows-10-Spying#4]
program is no running from a network share.
TODO: Fix

**Comment by cyberponk** [comment]
Same here!

**Comment by TRoskop** [comment]
This problem can be solved:
The program should check on start whether is is on a network share or not. 
If it is, it should copy itself to %temp% and start there. 

This is also the way VisualStudio-Setup etc. works...

**Comment by Nummer** [comment]
TRoskop, ok) thx)

**Comment by Nummer** [comment]
FIX
