### ISSUE TITLE
Continually crashes 

### ISSUE THREAD

**Issue by bpercival** [Nummer/Destroy-Windows-10-Spying#41]
After running the program, I receive a "Destroy Windows 10 Spying has stopped working", It goes through adding Windows Firewall rules, Ip list blocked, Disable private settings and the last entry seen is 'Disable Windows Defender'. 

If I Enable professional mode and unselect Disable windows defender, then it crashes on Disable private settings. So, I figured it was the next task so it finally completes if I unselect 'Set default windows photo viewer'

**Comment by Nummer** [comment]
Fixed in https://github.com/Nummer/Destroy-Windows-10-Spying/releases/tag/1.5.345
