### ISSUE TITLE
Windows Search doesn't work

### ISSUE THREAD

**Issue by superfedya** [Nummer/Destroy-Windows-10-Spying#42]
After use this program W10 search stop working even for local programs and files.

Any fix?

**Comment by Nummer** [comment]
sorry. Bug.

TODO: Fix

**Comment by an0ngh0st** [comment]
Is there anything we can do while we wait for the fix?

**Comment by AshTR** [comment]
http://www.voidtools.com/

I recommend Everything as an alternative. I used it back when Search in Windows 7 had problems for me.
