### ISSUE TITLE
Skype

### ISSUE THREAD

**Issue by goldjee** [Nummer/Destroy-Windows-10-Spying#43]
Blocks skype conference calls and Skype history sync

**Comment by TRoskop** [comment]
I someone wants to use this app to prevent spying, I don't think this person also wants to use skype. Skype also spies on you! There are better open-source solutions.

**Comment by goldjee** [comment]
Sure but it would great if the program had informed me about those little drawbacks. Or gave a possibility to opt-out from blocking non windows-related spying. Also if one wants full privacy, he'd prefer using Tails, not Windows.

**Comment by Nummer** [comment]
remove live.com host, in hosts file
