### ISSUE TITLE
Patch for german language!

### ISSUE THREAD

**Issue by TRoskop** [Nummer/Destroy-Windows-10-Spying#47]
Hello "Nummer",

I very enjoy you app and it does a good job.
To improve the user experience for German users I created a German language file (de-DE).
You can download the changed files from here (files compressed as zip): http://1drv.ms/1Q1BuGQ
Please include this patches to you code.

Note: I also made to changes in the "DestroyWindowsSpyingMainForm.cs"-File. This file is also included in the zip-file. I commented both changes, look for comments with an 'TR:' in string!

If you have questions etc., please write me an email: bug-report-roskop-2015@outlook.com

Best regards from Germany,
Thomas Roskop

**Comment by Nummer** [comment]
ok. Thx. Please  use pull request
