### ISSUE TITLE
блокирвока сайта http://www.deezer.com/

### ISSUE THREAD

**Issue by jackxb** [Nummer/Destroy-Windows-10-Spying#53]
Добрый вечер. Заметил один момент, если включено правило 185.13.160.61_Block, то сайт http://www.deezer.com/ перестет функционаровать (http://prntscr.com/8f88ca), отключив это правило, сайт снова работает.
Версия приложения 1.5.361.0. Возможно эта информация будет полезна Вам.

**Comment by Nummer** [comment]
профикшу в будущем апдейте

**Comment by Nummer** [comment]
фикс
