### ISSUE TITLE
Windows store apps download issue

### ISSUE THREAD

**Issue by beta-tank** [Nummer/Destroy-Windows-10-Spying#54]
When i try download app from Windows store (W10x64) I get **80072efd** error. When i remove from hosts:
* 0.0.0.0 statsfe2.update.microsoft.com.akadns.net 
* 0.0.0.0 sls.update.microsoft.com.akadns.net 
* 0.0.0.0 fe2.update.microsoft.com.akadns.net 

all be good. Can you add thease urls as option in pro mode for people who want use windows store?
And Mail (W10 app) cant load mails from outlook account. Maybe DWS block it?

**Comment by Nummer** [comment]
0.0.0.0 statsfe2.update.microsoft.com.akadns.net
0.0.0.0 sls.update.microsoft.com.akadns.net
0.0.0.0 fe2.update.microsoft.com.akadns.net

spying hosts.
