### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by malware1-2** [Nummer/Destroy-Windows-10-Spying#55]
Hello,
I don't know how to create a pull request, so I'm sharing this here.
Here's the Polish translation of DWS: http://m1.malwarehunterteam.com/files/DWS.zip
I can also translate the readme file, but can you tell me what these lines mean?
"HOSTS forced changes. Problems should not occur.
A more expanded the Delete menu applications."
Regards.

**Comment by TRoskop** [comment]
Hello malware1-2,
thanks for doing this job!

I created the complete pull requests for you! See here: https://github.com/Nummer/Destroy-Windows-10-Spying/pull/57

**Comment by malware1-2** [comment]
Thanks a lot! But "pl-PL | Polnish" should be changed to "pl-PL | Polish".

**Comment by TRoskop** [comment]
Uups :(   
Thanks. Fixed it!

**Comment by Nummer** [comment]
add
