### ISSUE TITLE
Unable to use some features

### ISSUE THREAD

**Issue by affandi3** [Nummer/Destroy-Windows-10-Spying#60]
Hello there DWS developer,

I'm not sure whether this is a bug or not, but I can't use professional mode and the features in utilities tab as they were greyed out. I'm using Windows 8.1.
I hope to get a quick reply from you.

Best Regards
![2015-09-16_13-33-20](https://cloud.githubusercontent.com/assets/14311768/9903736/02ba3d8a-5c79-11e5-9655-eb1d1abb762c.jpg)
![2015-09-16_13-36-53](https://cloud.githubusercontent.com/assets/14311768/9903737/02ba9988-5c79-11e5-9550-7e2feb0631c6.jpg)

**Comment by TRoskop** [comment]
Hi,
I checked this issue on Windows using the latest DWS_Lite build.
I found no problem!

Check the Log-File (dws.log, same directory as the .EXE!).

![win10](https://cloud.githubusercontent.com/assets/13079737/9906389/31fb184c-5c8a-11e5-8336-1a7f6820d977.png)
![win10-2](https://cloud.githubusercontent.com/assets/13079737/9906390/31fcb166-5c8a-11e5-966e-2560655d906f.png)

**Comment by affandi3** [comment]
Hi,

I have checked the log file, but there is nothing helpful on that file.
By the way, are you using Windows 10 ? Mine is Windows 8.1, so i guess there is a little problem with compatibility. 
![2015-09-16_16-27-24](https://cloud.githubusercontent.com/assets/14311768/9907752/d57c93b4-5c90-11e5-9170-9fb824fff474.jpg)
.

**Comment by TRoskop** [comment]
Oh, I forgot you are using Win8.1! 
Of course DWS_Lite removes some checkboxes as they are not available on other OS's than Win10.  

Just upgrade to Win10 and you will get those checkboxes :smile:
