### ISSUE TITLE
DWS is unusable with large (high DPI) fonts

### ISSUE THREAD

**Issue by pspot2** [Nummer/Destroy-Windows-10-Spying#63]
Hello,

first of all, awesome app! Well done!

With large fonts (I need this setup because I use my TV as a monitor) DWS does not automatically scale the UI. It is impossible to read anything, the texts are truncated. Also there is no possibility to resize the window manually.

Can be reproduced by setting a bigger font size (DPI larger than 96) in Windows 7.

Thanks.

**Comment by Nummer** [comment]
TODO: Fix

**Comment by Nummer** [comment]
Fixed in new version
