### ISSUE TITLE
Metro apps don't work after applying the patch

### ISSUE THREAD

**Issue by lx6g** [Nummer/Destroy-Windows-10-Spying#66]
- Store app can't install any app from the marketspace.
- Weather app can't update ... weather!
- Mail app can't get any new emails
- Calendar app can't connect to calendar servers

This happens with both the latest and previous releases.

**Comment by TRoskop** [comment]
@lx6g,
this is because some of the web services those apps are using have been blocked by DWS_Lite.
If you need them, just revert the changes.
