### ISSUE TITLE
Build 430: Utilities/Settings are greyed out on Windows 7/8

### ISSUE THREAD

**Issue by ryzhovau** [Nummer/Destroy-Windows-10-Spying#68]
No any buttons or checkboxes are available on Utilities or Settings page. It's all grey!

**Comment by pspot2** [comment]
I second that. In Windows 7 everything is inactive.

**Comment by TRoskop** [comment]
You can only have the button when you're using Win 10.

**Comment by ryzhovau** [comment]
@TRoskop, thanks. 

Better to add some comment about it.
@Nummer?

**Comment by ryzhovau** [comment]
Or implement Update turn off/on on Win7/8.

**Comment by Nummer** [comment]
@ryzhovau , tabs "Settings" , "Utilites" works only on windows 10.
