### ISSUE TITLE
Windows 10 Enterprise Stuck

### ISSUE THREAD

**Issue by LukanR** [Nummer/Destroy-Windows-10-Spying#73]
VM Ware Windows 10 Enterprise
Visual studio enterprise 2015
no/Office
SQL Server 2014
no connected to the internet
It gets stuck after Delete Voice Recorder

**Comment by LukanR** [comment]
I just opened Task Manager and in Local Host: Local System
stopped the Windows Update process and it finish it's work
Don't know if it did it ok

**Comment by Nummer** [comment]
=\
Sry, i do not understand u
