### ISSUE TITLE
I have a problem !

### ISSUE THREAD

**Issue by kasunkbp** [Nummer/Destroy-Windows-10-Spying#75]
Dear Sir.
This Great Tool destroying windows spying perfectly.
but i can't use professional mode & utilities.
please lookout  <a href=http://bit.ly/1NP9PLU>This Video.</a>
please give a solution.
Thank you.

**Comment by TRoskop** [comment]
as I already said here https://github.com/Nummer/Destroy-Windows-10-Spying/issues/60#issuecomment-140769950, you cannot use the features on other OSes than Windows 10.
This features only work with Windows 10.

**Comment by kasunkbp** [comment]
Thank You sir

**Comment by Nummer** [comment]
thx @TRoskop .
