### ISSUE TITLE
баг при открытие на серверной версии windows server 2012 R2 (rus)

### ISSUE THREAD

**Issue by DJSlider** [Nummer/Destroy-Windows-10-Spying#76]
Привет. Когда открываешь твою утилиту билд 433 на Windows server 2012 R2 (rus) вылезает ошибка вот эта.
скриншот прилагаю
P.S Спасибо, что добавил поддержку для сервера, неоднократно просил об этом в твоем твиттере
и на странице проекта в описании  удали лишний 0  где написано про поддержку винды серверной написал windows server 20012 

![default](https://cloud.githubusercontent.com/assets/14618047/10001713/c3358980-60ab-11e5-81b5-36f7fe416548.jpg)

**Comment by Nummer** [comment]
убери галку "Создавать точку восстановления в системе"

**Comment by DJSlider** [comment]
Я понял, игнорю  эту надпись. Она появляется сразу при открытие программы. и пункта создать точку восстановления нету, как и профессионального режима. Активна только кнопка удаления шпионов.

**Comment by DJSlider** [comment]
https://github.com/Nummer/Destroy-Windows-10-Spying/releases/tag/1.5.433

в описании поправь
Delete NEW SPYING UPDATE in windows 7/8/server 2008/             server 20012!

**Comment by Nummer** [comment]
всё
