### ISSUE TITLE
Metro apps cannot removed

### ISSUE THREAD

**Issue by ifyr** [Nummer/Destroy-Windows-10-Spying#78]
All versions between 430 and 433, can not remove metro apps.

Logs are as followes. But apps does not removed(System restarted)
  ==============
[INFO] Latest version number: 433
[INFO] Starting: 2015-09-22 10:17:36.
[INFO] Product Name: Windows 10 Enterprise
  Build: 10240.16463.amd64fre.th1.150819-1946
  ==========================
[INFO] Delete builder 3D
[INFO] Delete Camera
[INFO] Delete Mail, Calendar, Maps
[INFO] Delete Money, Sports, News and Weather
[INFO] Delete Groove Music and Film TV
[INFO] Delete People and OneNote
[INFO] Delete Phone Companion
[INFO] Delete Photos
[INFO] Delete Solitaire Collection
[INFO] Delete Voice Recorder
[INFO] Delete XBOX

**Comment by Nummer** [comment]
Hmm.... Disable you antivirus.

**Comment by ifyr** [comment]
Thank you very much.
But I do not have any antivirus software on my PC.
And the Windows Defender are disabled.
