### ISSUE TITLE
Utilities layout is not correct

### ISSUE THREAD

**Issue by rocker19943** [Nummer/Destroy-Windows-10-Spying#87]
![capture](https://cloud.githubusercontent.com/assets/12564383/10108390/b4aeb084-63d1-11e5-8669-cef2248d9b0f.PNG)

I'm not sure if you have decided to design this section just like this... its too unconfortable
Please fix the button placements

**Comment by Pegas1606** [comment]
When the program switch to professional mode, it will look better.

**Comment by TRoskop** [comment]
This new code ( https://github.com/Nummer/Destroy-Windows-10-Spying/pull/90 ) should correct the ui-layout as it uses new UI-technologies.

**Comment by rocker19943** [comment]
In case if you dont want to change the ui framework i suggess you to use this like form...

![Non Pro Mode](https://cloud.githubusercontent.com/assets/12564383/10122606/238aca24-6530-11e5-80b7-d019a67fe054.PNG)

![Pro Mode](https://cloud.githubusercontent.com/assets/12564383/10122607/2cd491fa-6530-11e5-968c-3fe64d186e0d.PNG)

**Comment by Nummer** [comment]
thx
