### ISSUE TITLE
UI Layout Design

### ISSUE THREAD

**Issue by TRoskop** [Nummer/Destroy-Windows-10-Spying#88]
Hello @Nummer,
this app uses WinForms to show the UI.

However, Winforms are out-of-date. Modern system with touch and high-resolution-devices are not supported. 

Do you want to migrate the UI (onyl the ui!) to XAML? Or would you like someone else (me) to do so?

**Comment by rocker19943** [comment]
there is an option to go with QT which is modern and powerfull

**Comment by TRoskop** [comment]
QT is a very powerfull and good framework, but it ist not the best for Windows. It focuses more on platform independence (runs on windows, os x, linux...).
For Windows and .NET, WPF is currenly the best as it also supports hardware acceleration using DirectX etc. 
Moreover, the new windows store apps are also build using XAML.

**Comment by Nummer** [comment]
cool. Please add me to you contact list in skype. My skype: n.u.m.m.e.r

**Comment by TRoskop** [comment]
Added to skype.
