### ISSUE TITLE
Вторая локальная учетная запись

### ISSUE THREAD

**Issue by shurff** [Nummer/Destroy-Windows-10-Spying#91]
На компьютере две локальных учетных записи под Windows 10. Первая администратора, вторая обычного пользователя. При запуске DWS, из под администратора, все ненужные программы в этой учетной записи удаляются. При переходе на обычную учетную запись оказывается, что все удаленные в учетной записи администратора не нужные программы здесь сохранились. Если из под учетной записи обычного пользователя запустить DWS опять, программа работает но в учетной записи обычного пользователя ни одна программа не удаляется. Исправьте пожалуйста

**Comment by Nummer** [comment]
Это особенность Windows
