### ISSUE TITLE
Wish

### ISSUE THREAD

**Issue by evgeniy1000** [Nummer/Destroy-Windows-10-Spying#93]
Hello! Please enter the program to automatically update and that the program has been a constant running in the system tray. Thank you!

**Comment by TRoskop** [comment]
Hello @evgeniy1000 ,
the newer builds are able to update themselves.
When launching the app it checks for newer versions and downloads them if available.

And why should it run in background? This consumes RAM and process time?

**Comment by evgeniy1000** [comment]
Hello, if auto-update win, it is necessary to regularly download the new
version of your software and check regularly for the absence of spyware. I
think a lot of RAM it will not eat. I wish that the program itself is
regularly checked for spyware. You can, in principle, by the scheduler so
that the program does not run continuously
Thank you!

2015-09-28 20:59 GMT+05:00 Thomas Roskop <notifications@github.com>:
