### ISSUE TITLE
Automatic log of actions saved to disk

### ISSUE THREAD

**Issue by zeroZshadow** [Nummer/Destroy-Windows-10-Spying#97]
The log of all actions taken should be written to disk after "Destroy windows 10 spying" is completed
An accurate log of what group policy was changed, etc; would be greatly helpfull to undo an option that was checked by accident.

**Comment by Nummer** [comment]
sry, i do not understand you

**Comment by TRoskop** [comment]
He simply wants to have a complete log. Every single change should be recorded.

**Comment by zeroZshadow** [comment]
And more importantly, to save this log on disk. Since after you hit the restart button or close the tool, the log is gone.
