### ISSUE TITLE
List actions to be taken before actually running

### ISSUE THREAD

**Issue by zeroZshadow** [Nummer/Destroy-Windows-10-Spying#98]
When "Destroy windows 10 spying" is clicked, a list of all to be taken actions should be displayed for verifycation.
This is because it is unclear what the tool will block and disable.

An example, it disabled windows defender for me, which I was unaware off. (I forgot to uncheck it)
Since there is no log (see my other issue) it was difficult to fix afterwards.

A simple confirmation would have prevented this.

**Comment by Nummer** [comment]
TODO: fix
