### ISSUE TITLE
Font About Tab

### ISSUE THREAD

**Issue by Slankman** [Nummer/Destroy-Windows-10-Spying#99]
like the font used in build 423 build under the about section new versions hard to read

**Comment by DanWillman** [comment]
Do you mean here?
![image](https://cloud.githubusercontent.com/assets/4489280/10262881/f3e11dc2-699f-11e5-8d5f-65c4e0f4c2b0.png)

**Comment by Slankman** [comment]
very minor but could read in build 423 any build after cannot view clearly could be my ips monitor or video drivers not sure otherwise great program

**Comment by DanWillman** [comment]
:+1: I changed the font and submitted a pull request, is this better?

![image](http://i.imgur.com/5a349xw.png)

**Comment by Slankman** [comment]
looks great !! viewable on my end

**Comment by Nummer** [comment]
=\
